// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AchPaymentMethod struct {
	Last4    *string `json:"last4,omitempty"`
	BankName *string `json:"bankName,omitempty"`
}

func (a *AchPaymentMethod) GetLast4() *string {
	if a == nil {
		return nil
	}
	return a.Last4
}

func (a *AchPaymentMethod) GetBankName() *string {
	if a == nil {
		return nil
	}
	return a.BankName
}
