// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AppConfigWithServiceConfig struct {
	ServiceConfig *ServiceConfigWrite `json:"serviceConfig,omitempty"`
	// Configure [player authentication](https://hathora.dev/docs/backend-integrations/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
	AuthConfiguration AuthConfiguration `json:"authConfiguration"`
	// Readable name for an application. Must be unique within an organization.
	AppName string `json:"appName"`
}

func (a *AppConfigWithServiceConfig) GetServiceConfig() *ServiceConfigWrite {
	if a == nil {
		return nil
	}
	return a.ServiceConfig
}

func (a *AppConfigWithServiceConfig) GetAuthConfiguration() AuthConfiguration {
	if a == nil {
		return AuthConfiguration{}
	}
	return a.AuthConfiguration
}

func (a *AppConfigWithServiceConfig) GetAppName() string {
	if a == nil {
		return ""
	}
	return a.AppName
}
