// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type ApplicationWithLatestDeploymentAndBuildServiceConfig struct {
	// The configuration for the Process Autoscaler for this application.
	// Autoscaling must be enabled on a per-region basis.
	// EXPERIMENTAL - This feature is in closed beta.
	ProcessAutoscalerConfig *ProcessAutoscalerConfig `json:"processAutoscalerConfig,omitempty"`
	LoadBalancer            *LoadBalancerConfig      `json:"loadBalancer,omitempty"`
	// The headroom configuration for each region.
	// EXPERIMENTAL - this feature is in closed beta.
	StaticProcessAllocation []StaticProcessAllocationConfig `json:"staticProcessAllocation"`
}

func (a *ApplicationWithLatestDeploymentAndBuildServiceConfig) GetProcessAutoscalerConfig() *ProcessAutoscalerConfig {
	if a == nil {
		return nil
	}
	return a.ProcessAutoscalerConfig
}

func (a *ApplicationWithLatestDeploymentAndBuildServiceConfig) GetLoadBalancer() *LoadBalancerConfig {
	if a == nil {
		return nil
	}
	return a.LoadBalancer
}

func (a *ApplicationWithLatestDeploymentAndBuildServiceConfig) GetStaticProcessAllocation() []StaticProcessAllocationConfig {
	if a == nil {
		return []StaticProcessAllocationConfig{}
	}
	return a.StaticProcessAllocation
}

type ApplicationWithLatestDeploymentAndBuildEnv struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

func (a *ApplicationWithLatestDeploymentAndBuildEnv) GetValue() string {
	if a == nil {
		return ""
	}
	return a.Value
}

func (a *ApplicationWithLatestDeploymentAndBuildEnv) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

type ApplicationWithLatestDeploymentAndBuildDeployment struct {
	// The id of the fleet.
	FleetID *string `json:"fleetId,omitempty"`
	// Arbitrary metadata associated with a deployment.
	DeploymentTag *string `json:"deploymentTag,omitempty"`
	// Option to shut down processes that have had no new connections or rooms
	// for five minutes.
	IdleTimeoutEnabled bool `json:"idleTimeoutEnabled"`
	// The environment variable that our process will have access to at runtime.
	Env []ApplicationWithLatestDeploymentAndBuildEnv `json:"env"`
	// Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
	RoomsPerProcess int `json:"roomsPerProcess"`
	// Additional ports your server listens on.
	AdditionalContainerPorts []ContainerPort `json:"additionalContainerPorts"`
	// A container port object represents the transport configruations for how your server will listen.
	DefaultContainerPort ContainerPort `json:"defaultContainerPort"`
	// When the deployment was created.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// The number of GPUs allocated to your process. Must be an integer.
	// If not provided, the requested GPU is 0.
	RequestedGPU *float64 `json:"requestedGPU,omitempty"`
	// EXPERIMENTAL - this feature is in closed beta.
	// The number of GPUs allocated to your process. Must be an integer.
	// If not provided, the requested GPU is 0.
	ExperimentalRequestedGPU *float64 `json:"experimentalRequestedGPU,omitempty"`
	// The amount of memory allocated to your process. By default, this is capped
	// at 8192 MB, but can be increased further on the Enterprise tier.
	RequestedMemoryMB float64 `json:"requestedMemoryMB"`
	// The number of cores allocated to your process.
	RequestedCPU float64 `json:"requestedCPU"`
	// System generated id for a deployment.
	DeploymentID string `json:"deploymentId"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuild()`](https://hathora.dev/api#tag/BuildsV3/operation/GetBuild).
	BuildTag *string `json:"buildTag,omitempty"`
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID string `json:"buildId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
	// A build represents a game server artifact and its associated metadata.
	Build BuildV3 `json:"build"`
}

func (a ApplicationWithLatestDeploymentAndBuildDeployment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"idleTimeoutEnabled", "env", "roomsPerProcess", "additionalContainerPorts", "defaultContainerPort", "createdAt", "createdBy", "requestedMemoryMB", "requestedCPU", "deploymentId", "buildId", "appId", "build"}); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetFleetID() *string {
	if a == nil {
		return nil
	}
	return a.FleetID
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetDeploymentTag() *string {
	if a == nil {
		return nil
	}
	return a.DeploymentTag
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetIdleTimeoutEnabled() bool {
	if a == nil {
		return false
	}
	return a.IdleTimeoutEnabled
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetEnv() []ApplicationWithLatestDeploymentAndBuildEnv {
	if a == nil {
		return []ApplicationWithLatestDeploymentAndBuildEnv{}
	}
	return a.Env
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetRoomsPerProcess() int {
	if a == nil {
		return 0
	}
	return a.RoomsPerProcess
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetAdditionalContainerPorts() []ContainerPort {
	if a == nil {
		return []ContainerPort{}
	}
	return a.AdditionalContainerPorts
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetDefaultContainerPort() ContainerPort {
	if a == nil {
		return ContainerPort{}
	}
	return a.DefaultContainerPort
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetRequestedGPU() *float64 {
	if a == nil {
		return nil
	}
	return a.RequestedGPU
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetExperimentalRequestedGPU() *float64 {
	if a == nil {
		return nil
	}
	return a.ExperimentalRequestedGPU
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetRequestedMemoryMB() float64 {
	if a == nil {
		return 0.0
	}
	return a.RequestedMemoryMB
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetRequestedCPU() float64 {
	if a == nil {
		return 0.0
	}
	return a.RequestedCPU
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetDeploymentID() string {
	if a == nil {
		return ""
	}
	return a.DeploymentID
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetBuildTag() *string {
	if a == nil {
		return nil
	}
	return a.BuildTag
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetBuildID() string {
	if a == nil {
		return ""
	}
	return a.BuildID
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetAppID() string {
	if a == nil {
		return ""
	}
	return a.AppID
}

func (a *ApplicationWithLatestDeploymentAndBuildDeployment) GetBuild() BuildV3 {
	if a == nil {
		return BuildV3{}
	}
	return a.Build
}

// ApplicationWithLatestDeploymentAndBuild - An application object is the top level namespace for the game server.
type ApplicationWithLatestDeploymentAndBuild struct {
	// The email address or token id for the user that deleted the application.
	DeletedBy *string `json:"deletedBy"`
	// When the application was deleted.
	DeletedAt *time.Time `json:"deletedAt"`
	// When the application was created.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// System generated unique identifier for an organization. Not guaranteed to have a specific format.
	OrgID         string                                                `json:"orgId"`
	ServiceConfig *ApplicationWithLatestDeploymentAndBuildServiceConfig `json:"serviceConfig"`
	// Configure [player authentication](https://hathora.dev/docs/backend-integrations/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
	AuthConfiguration AuthConfiguration `json:"authConfiguration"`
	// Secret that is used for identity and access management.
	AppSecret string `json:"appSecret"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
	// Readable name for an application. Must be unique within an organization.
	AppName    string                                             `json:"appName"`
	Deployment *ApplicationWithLatestDeploymentAndBuildDeployment `json:"deployment,omitempty"`
}

func (a ApplicationWithLatestDeploymentAndBuild) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationWithLatestDeploymentAndBuild) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"deletedBy", "deletedAt", "createdAt", "createdBy", "orgId", "serviceConfig", "authConfiguration", "appSecret", "appId", "appName"}); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetDeletedBy() *string {
	if a == nil {
		return nil
	}
	return a.DeletedBy
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetDeletedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DeletedAt
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetServiceConfig() *ApplicationWithLatestDeploymentAndBuildServiceConfig {
	if a == nil {
		return nil
	}
	return a.ServiceConfig
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetAuthConfiguration() AuthConfiguration {
	if a == nil {
		return AuthConfiguration{}
	}
	return a.AuthConfiguration
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetAppSecret() string {
	if a == nil {
		return ""
	}
	return a.AppSecret
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetAppID() string {
	if a == nil {
		return ""
	}
	return a.AppID
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetAppName() string {
	if a == nil {
		return ""
	}
	return a.AppName
}

func (a *ApplicationWithLatestDeploymentAndBuild) GetDeployment() *ApplicationWithLatestDeploymentAndBuildDeployment {
	if a == nil {
		return nil
	}
	return a.Deployment
}
