// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ApplicationsPage struct {
	Applications []ApplicationWithLatestDeploymentAndBuild `json:"applications"`
}

func (a *ApplicationsPage) GetApplications() []ApplicationWithLatestDeploymentAndBuild {
	if a == nil {
		return []ApplicationWithLatestDeploymentAndBuild{}
	}
	return a.Applications
}
