// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricName - The name of the metric.
// Allowed values:
// `concurrent-requests`: Tracks the number of concurrent requests that a single Process handles.
type MetricName string

const (
	MetricNameConcurrentRequests MetricName = "concurrent-requests"
)

func (e MetricName) ToPointer() *MetricName {
	return &e
}

type AutoscalerTargetMetric struct {
	MetricValue float64 `json:"metricValue"`
	// The name of the metric.
	// Allowed values:
	// `concurrent-requests`: Tracks the number of concurrent requests that a single Process handles.
	MetricName MetricName `json:"metricName"`
}

func (o *AutoscalerTargetMetric) GetMetricValue() float64 {
	if o == nil {
		return 0.0
	}
	return o.MetricValue
}

func (o *AutoscalerTargetMetric) GetMetricName() MetricName {
	if o == nil {
		return MetricName("")
	}
	return o.MetricName
}
