// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MetricName - The name of the metric.
// Allowed values:
// `concurrent-requests`: Tracks the number of concurrent requests that a single Process handles.
type MetricName string

const (
	MetricNameConcurrentRequests MetricName = "concurrent-requests"
)

func (e MetricName) ToPointer() *MetricName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MetricName) IsExact() bool {
	if e != nil {
		switch *e {
		case "concurrent-requests":
			return true
		}
	}
	return false
}

type AutoscalerTargetMetric struct {
	MetricValue float64 `json:"metricValue"`
	// The name of the metric.
	// Allowed values:
	// `concurrent-requests`: Tracks the number of concurrent requests that a single Process handles.
	MetricName MetricName `json:"metricName"`
}

func (a *AutoscalerTargetMetric) GetMetricValue() float64 {
	if a == nil {
		return 0.0
	}
	return a.MetricValue
}

func (a *AutoscalerTargetMetric) GetMetricName() MetricName {
	if a == nil {
		return MetricName("")
	}
	return a.MetricName
}
