// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AutoscalerConfig struct {
	// If vCPU utilization rate is above this threshold percentage, the autoscaler will scale up.
	// If set to 100 this disables preemptive autoscaling (i.e. nodes will only scale up when you
	// run out of capacity and request more resources).
	ScaleUpThreshold int `json:"scaleUpThreshold"`
}

func (o *AutoscalerConfig) GetScaleUpThreshold() int {
	if o == nil {
		return 0
	}
	return o.ScaleUpThreshold
}
