// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BuildPart struct {
	PutRequestURL string  `json:"putRequestUrl"`
	PartNumber    float64 `json:"partNumber"`
}

func (b *BuildPart) GetPutRequestURL() string {
	if b == nil {
		return ""
	}
	return b.PutRequestURL
}

func (b *BuildPart) GetPartNumber() float64 {
	if b == nil {
		return 0.0
	}
	return b.PartNumber
}
