// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BuildStatus string

const (
	BuildStatusCreated   BuildStatus = "created"
	BuildStatusRunning   BuildStatus = "running"
	BuildStatusSucceeded BuildStatus = "succeeded"
	BuildStatusFailed    BuildStatus = "failed"
)

func (e BuildStatus) ToPointer() *BuildStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BuildStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "created", "running", "succeeded", "failed":
			return true
		}
	}
	return false
}
