// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

// BuildV3 - A build represents a game server artifact and its associated metadata.
type BuildV3 struct {
	// When the build expired
	ExpiredAt *time.Time `json:"expiredAt,omitempty"`
	// Url to view details, like build logs, of the build.
	ShareURL    *string `json:"shareUrl,omitempty"`
	ContentHash *string `json:"contentHash,omitempty"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuild()`](https://hathora.dev/api#tag/BuildsV3/operation/GetBuild).
	BuildTag *string `json:"buildTag,omitempty"`
	// The size (in bytes) of the Docker image built by Hathora.
	ImageSize int64       `json:"imageSize"`
	Status    BuildStatus `json:"status"`
	// When the build was deleted.
	DeletedAt *time.Time `json:"deletedAt"`
	// When [`RunBuild()`](https://hathora.dev/api#tag/BuildV2/operation/RunBuild) finished executing.
	FinishedAt *time.Time `json:"finishedAt"`
	// When [`RunBuild()`](https://hathora.dev/api#tag/BuildV2/operation/RunBuild) is called.
	StartedAt *time.Time `json:"startedAt"`
	// When [`CreateBuild()`](https://hathora.dev/api#tag/BuildV2/operation/CreateBuild) is called.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID string `json:"buildId"`
	// System generated unique identifier for an organization. Not guaranteed to have a specific format.
	OrgID string `json:"orgId"`
}

func (b BuildV3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildV3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"imageSize", "status", "createdAt", "createdBy", "buildId", "orgId"}); err != nil {
		return err
	}
	return nil
}

func (b *BuildV3) GetExpiredAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ExpiredAt
}

func (b *BuildV3) GetShareURL() *string {
	if b == nil {
		return nil
	}
	return b.ShareURL
}

func (b *BuildV3) GetContentHash() *string {
	if b == nil {
		return nil
	}
	return b.ContentHash
}

func (b *BuildV3) GetBuildTag() *string {
	if b == nil {
		return nil
	}
	return b.BuildTag
}

func (b *BuildV3) GetImageSize() int64 {
	if b == nil {
		return 0
	}
	return b.ImageSize
}

func (b *BuildV3) GetStatus() BuildStatus {
	if b == nil {
		return BuildStatus("")
	}
	return b.Status
}

func (b *BuildV3) GetDeletedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.DeletedAt
}

func (b *BuildV3) GetFinishedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.FinishedAt
}

func (b *BuildV3) GetStartedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.StartedAt
}

func (b *BuildV3) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BuildV3) GetCreatedBy() string {
	if b == nil {
		return ""
	}
	return b.CreatedBy
}

func (b *BuildV3) GetBuildID() string {
	if b == nil {
		return ""
	}
	return b.BuildID
}

func (b *BuildV3) GetOrgID() string {
	if b == nil {
		return ""
	}
	return b.OrgID
}
