// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type RegionalContainerTags struct {
	ContainerTag string `json:"containerTag"`
	Region       Region `json:"region"`
}

func (r *RegionalContainerTags) GetContainerTag() string {
	if r == nil {
		return ""
	}
	return r.ContainerTag
}

func (r *RegionalContainerTags) GetRegion() Region {
	if r == nil {
		return Region("")
	}
	return r.Region
}

// Build - A build represents a game server artifact and its associated metadata.
type Build struct {
	// When the build expired
	ExpiredAt *time.Time `json:"expiredAt,omitempty"`
	BuildTag  *string    `json:"buildTag,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RegionalContainerTags []RegionalContainerTags `json:"regionalContainerTags"`
	// The size (in bytes) of the Docker image built by Hathora.
	ImageSize int64       `json:"imageSize"`
	Status    BuildStatus `json:"status"`
	// When the build was deleted.
	DeletedAt *time.Time `json:"deletedAt"`
	// When [`RunBuild()`](https://hathora.dev/api#tag/BuildV2/operation/RunBuild) finished executing.
	FinishedAt *time.Time `json:"finishedAt"`
	// When [`RunBuild()`](https://hathora.dev/api#tag/BuildV2/operation/RunBuild) is called.
	StartedAt *time.Time `json:"startedAt"`
	// When [`CreateBuild()`](https://hathora.dev/api#tag/BuildV2/operation/CreateBuild) is called.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// System generated id for a build. Increments by 1.
	BuildID int `json:"buildId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
}

func (b Build) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Build) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"regionalContainerTags", "imageSize", "status", "deletedAt", "finishedAt", "startedAt", "createdAt", "createdBy", "buildId", "appId"}); err != nil {
		return err
	}
	return nil
}

func (b *Build) GetExpiredAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.ExpiredAt
}

func (b *Build) GetBuildTag() *string {
	if b == nil {
		return nil
	}
	return b.BuildTag
}

func (b *Build) GetRegionalContainerTags() []RegionalContainerTags {
	if b == nil {
		return []RegionalContainerTags{}
	}
	return b.RegionalContainerTags
}

func (b *Build) GetImageSize() int64 {
	if b == nil {
		return 0
	}
	return b.ImageSize
}

func (b *Build) GetStatus() BuildStatus {
	if b == nil {
		return BuildStatus("")
	}
	return b.Status
}

func (b *Build) GetDeletedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.DeletedAt
}

func (b *Build) GetFinishedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.FinishedAt
}

func (b *Build) GetStartedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.StartedAt
}

func (b *Build) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *Build) GetCreatedBy() string {
	if b == nil {
		return ""
	}
	return b.CreatedBy
}

func (b *Build) GetBuildID() int {
	if b == nil {
		return 0
	}
	return b.BuildID
}

func (b *Build) GetAppID() string {
	if b == nil {
		return ""
	}
	return b.AppID
}
