// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConnectionInfoV2 - Connection information for the default and additional ports.
type ConnectionInfoV2 struct {
	AdditionalExposedPorts []ExposedPort `json:"additionalExposedPorts"`
	// Connection details for an active process.
	ExposedPort *ExposedPort    `json:"exposedPort,omitempty"`
	Status      RoomReadyStatus `json:"status"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
}

func (c *ConnectionInfoV2) GetAdditionalExposedPorts() []ExposedPort {
	if c == nil {
		return []ExposedPort{}
	}
	return c.AdditionalExposedPorts
}

func (c *ConnectionInfoV2) GetExposedPort() *ExposedPort {
	if c == nil {
		return nil
	}
	return c.ExposedPort
}

func (c *ConnectionInfoV2) GetStatus() RoomReadyStatus {
	if c == nil {
		return RoomReadyStatus("")
	}
	return c.Status
}

func (c *ConnectionInfoV2) GetRoomID() string {
	if c == nil {
		return ""
	}
	return c.RoomID
}
