// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateBuildV3Params struct {
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID *string `json:"buildId,omitempty"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuild()`](https://hathora.dev/api#tag/BuildsV3/operation/GetBuild).
	BuildTag *string `json:"buildTag,omitempty"`
}

func (c *CreateBuildV3Params) GetBuildID() *string {
	if c == nil {
		return nil
	}
	return c.BuildID
}

func (c *CreateBuildV3Params) GetBuildTag() *string {
	if c == nil {
		return nil
	}
	return c.BuildTag
}
