// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatedOrgToken struct {
	PlainTextToken string   `json:"plainTextToken"`
	OrgToken       OrgToken `json:"orgToken"`
}

func (c *CreatedOrgToken) GetPlainTextToken() string {
	if c == nil {
		return ""
	}
	return c.PlainTextToken
}

func (c *CreatedOrgToken) GetOrgToken() OrgToken {
	if c == nil {
		return OrgToken{}
	}
	return c.OrgToken
}
