// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateRoomParams struct {
	// System generated id for a deployment.
	DeploymentID *string `json:"deploymentId,omitempty"`
	// An optional list of client IP addresses to whitelist for DDoS protection.
	ClientIPs []string `json:"clientIPs,omitempty"`
	// Optional configuration parameters for the room. Can be any string including stringified JSON. It is accessible from the room via [`GetRoomInfo()`](https://hathora.dev/api#tag/RoomV2/operation/GetRoomInfo).
	RoomConfig *string `json:"roomConfig,omitempty"`
	Region     Region  `json:"region"`
}

func (c *CreateRoomParams) GetDeploymentID() *string {
	if c == nil {
		return nil
	}
	return c.DeploymentID
}

func (c *CreateRoomParams) GetClientIPs() []string {
	if c == nil {
		return nil
	}
	return c.ClientIPs
}

func (c *CreateRoomParams) GetRoomConfig() *string {
	if c == nil {
		return nil
	}
	return c.RoomConfig
}

func (c *CreateRoomParams) GetRegion() Region {
	if c == nil {
		return Region("")
	}
	return c.Region
}
