// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateLobbyV3Params struct {
	// Types of lobbies a player can create.
	//
	// `private`: the player who created the room must share the roomId with their friends
	//
	// `public`: visible in the public lobby list, anyone can join
	//
	// `local`: for testing with a server running locally
	Visibility LobbyVisibility `json:"visibility"`
	// Optional configuration parameters for the room. Can be any string including stringified JSON. It is accessible from the room via [`GetRoomInfo()`](https://hathora.dev/api#tag/RoomV2/operation/GetRoomInfo).
	RoomConfig *string `json:"roomConfig,omitempty"`
	Region     Region  `json:"region"`
}

func (c *CreateLobbyV3Params) GetVisibility() LobbyVisibility {
	if c == nil {
		return LobbyVisibility("")
	}
	return c.Visibility
}

func (c *CreateLobbyV3Params) GetRoomConfig() *string {
	if c == nil {
		return nil
	}
	return c.RoomConfig
}

func (c *CreateLobbyV3Params) GetRegion() Region {
	if c == nil {
		return Region("")
	}
	return c.Region
}
