// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateFleet struct {
	NodeShape        *NodeShape        `json:"nodeShape,omitempty"`
	AutoscalerConfig *AutoscalerConfig `json:"autoscalerConfig,omitempty"`
}

func (c *CreateFleet) GetNodeShape() *NodeShape {
	if c == nil {
		return nil
	}
	return c.NodeShape
}

func (c *CreateFleet) GetAutoscalerConfig() *AutoscalerConfig {
	if c == nil {
		return nil
	}
	return c.AutoscalerConfig
}
