// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateLobbyParams struct {
	// Types of lobbies a player can create.
	//
	// `private`: the player who created the room must share the roomId with their friends
	//
	// `public`: visible in the public lobby list, anyone can join
	//
	// `local`: for testing with a server running locally
	Visibility LobbyVisibility `json:"visibility"`
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any    `json:"initialConfig"`
	Region        Region `json:"region"`
}

func (c *CreateLobbyParams) GetVisibility() LobbyVisibility {
	if c == nil {
		return LobbyVisibility("")
	}
	return c.Visibility
}

func (c *CreateLobbyParams) GetInitialConfig() any {
	if c == nil {
		return nil
	}
	return c.InitialConfig
}

func (c *CreateLobbyParams) GetRegion() Region {
	if c == nil {
		return Region("")
	}
	return c.Region
}
