// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateFleetV2 struct {
	NodeShapeID      NodeShapeID      `json:"nodeShapeId"`
	AutoscalerConfig AutoscalerConfig `json:"autoscalerConfig"`
	// Readable name for a fleet. Must be unique within an organization.
	Name string `json:"name"`
}

func (c *CreateFleetV2) GetNodeShapeID() NodeShapeID {
	if c == nil {
		return NodeShapeID("")
	}
	return c.NodeShapeID
}

func (c *CreateFleetV2) GetAutoscalerConfig() AutoscalerConfig {
	if c == nil {
		return AutoscalerConfig{}
	}
	return c.AutoscalerConfig
}

func (c *CreateFleetV2) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
