// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateMultipartBuildParams struct {
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID *string `json:"buildId,omitempty"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuild()`](https://hathora.dev/api#tag/BuildsV3/operation/GetBuild).
	BuildTag         *string `json:"buildTag,omitempty"`
	BuildSizeInBytes float64 `json:"buildSizeInBytes"`
}

func (c *CreateMultipartBuildParams) GetBuildID() *string {
	if c == nil {
		return nil
	}
	return c.BuildID
}

func (c *CreateMultipartBuildParams) GetBuildTag() *string {
	if c == nil {
		return nil
	}
	return c.BuildTag
}

func (c *CreateMultipartBuildParams) GetBuildSizeInBytes() float64 {
	if c == nil {
		return 0.0
	}
	return c.BuildSizeInBytes
}
