// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeploymentsV3Page struct {
	NextPageToken *string        `json:"nextPageToken,omitempty"`
	Deployments   []DeploymentV3 `json:"deployments"`
}

func (d *DeploymentsV3Page) GetNextPageToken() *string {
	if d == nil {
		return nil
	}
	return d.NextPageToken
}

func (d *DeploymentsV3Page) GetDeployments() []DeploymentV3 {
	if d == nil {
		return []DeploymentV3{}
	}
	return d.Deployments
}
