// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type Env struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

func (e *Env) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}

func (e *Env) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

// DeploymentV1TransportType
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type DeploymentV1TransportType string

const (
	DeploymentV1TransportTypeTCP DeploymentV1TransportType = "tcp"
	DeploymentV1TransportTypeUDP DeploymentV1TransportType = "udp"
	DeploymentV1TransportTypeTLS DeploymentV1TransportType = "tls"
)

func (e DeploymentV1TransportType) ToPointer() *DeploymentV1TransportType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeploymentV1TransportType) IsExact() bool {
	if e != nil {
		switch *e {
		case "tcp", "udp", "tls":
			return true
		}
	}
	return false
}

// DeploymentV1 - Deployment is a versioned configuration for a build that describes runtime behavior.
type DeploymentV1 struct {
	// Option to shut down processes that have had no new connections or rooms
	// for five minutes.
	IdleTimeoutEnabled *bool `default:"true" json:"idleTimeoutEnabled"`
	// The environment variable that our process will have access to at runtime.
	Env []Env `json:"env"`
	// Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
	RoomsPerProcess int `json:"roomsPerProcess"`
	// A plan defines how much CPU and memory is required to run an instance of your game server.
	//
	// `tiny`: shared core, 1gb memory
	//
	// `small`: 1 core, 2gb memory
	//
	// `medium`: 2 core, 4gb memory
	//
	// `large`: 4 core, 8gb memory
	PlanName PlanName `json:"planName"`
	// Additional ports your server listens on.
	AdditionalContainerPorts []ContainerPort `json:"additionalContainerPorts"`
	// A container port object represents the transport configruations for how your server will listen.
	DefaultContainerPort ContainerPort `json:"defaultContainerPort"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TransportType DeploymentV1TransportType `json:"transportType"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContainerPort float64 `json:"containerPort"`
	// When the deployment was created.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// The amount of memory allocated to your process.
	RequestedMemoryMB int `json:"requestedMemoryMB"`
	// The number of cores allocated to your process.
	RequestedCPU float64 `json:"requestedCPU"`
	// System generated id for a deployment. Increments by 1.
	DeploymentID int `json:"deploymentId"`
	// System generated id for a build. Increments by 1.
	BuildID int `json:"buildId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
}

func (d DeploymentV1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentV1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"env", "roomsPerProcess", "planName", "additionalContainerPorts", "defaultContainerPort", "transportType", "containerPort", "createdAt", "createdBy", "requestedMemoryMB", "requestedCPU", "deploymentId", "buildId", "appId"}); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentV1) GetIdleTimeoutEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.IdleTimeoutEnabled
}

func (d *DeploymentV1) GetEnv() []Env {
	if d == nil {
		return []Env{}
	}
	return d.Env
}

func (d *DeploymentV1) GetRoomsPerProcess() int {
	if d == nil {
		return 0
	}
	return d.RoomsPerProcess
}

func (d *DeploymentV1) GetPlanName() PlanName {
	if d == nil {
		return PlanName("")
	}
	return d.PlanName
}

func (d *DeploymentV1) GetAdditionalContainerPorts() []ContainerPort {
	if d == nil {
		return []ContainerPort{}
	}
	return d.AdditionalContainerPorts
}

func (d *DeploymentV1) GetDefaultContainerPort() ContainerPort {
	if d == nil {
		return ContainerPort{}
	}
	return d.DefaultContainerPort
}

func (d *DeploymentV1) GetTransportType() DeploymentV1TransportType {
	if d == nil {
		return DeploymentV1TransportType("")
	}
	return d.TransportType
}

func (d *DeploymentV1) GetContainerPort() float64 {
	if d == nil {
		return 0.0
	}
	return d.ContainerPort
}

func (d *DeploymentV1) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DeploymentV1) GetCreatedBy() string {
	if d == nil {
		return ""
	}
	return d.CreatedBy
}

func (d *DeploymentV1) GetRequestedMemoryMB() int {
	if d == nil {
		return 0
	}
	return d.RequestedMemoryMB
}

func (d *DeploymentV1) GetRequestedCPU() float64 {
	if d == nil {
		return 0.0
	}
	return d.RequestedCPU
}

func (d *DeploymentV1) GetDeploymentID() int {
	if d == nil {
		return 0
	}
	return d.DeploymentID
}

func (d *DeploymentV1) GetBuildID() int {
	if d == nil {
		return 0
	}
	return d.BuildID
}

func (d *DeploymentV1) GetAppID() string {
	if d == nil {
		return ""
	}
	return d.AppID
}
