// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeploymentConfigV2Env struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

func (d *DeploymentConfigV2Env) GetValue() string {
	if d == nil {
		return ""
	}
	return d.Value
}

func (d *DeploymentConfigV2Env) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type DeploymentConfigV2 struct {
	// Option to shut down processes that have had no new connections or rooms
	// for five minutes.
	IdleTimeoutEnabled bool `json:"idleTimeoutEnabled"`
	// The environment variable that our process will have access to at runtime.
	Env []DeploymentConfigV2Env `json:"env"`
	// Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
	RoomsPerProcess int `json:"roomsPerProcess"`
	// Additional ports your server listens on.
	AdditionalContainerPorts []ContainerPort `json:"additionalContainerPorts,omitempty"`
	// Transport type specifies the underlying communication protocol to the exposed port.
	TransportType TransportType `json:"transportType"`
	// Default port the server listens on.
	ContainerPort int `json:"containerPort"`
	// The amount of memory allocated to your process.
	RequestedMemoryMB float64 `json:"requestedMemoryMB"`
	// The number of cores allocated to your process.
	RequestedCPU float64 `json:"requestedCPU"`
}

func (d *DeploymentConfigV2) GetIdleTimeoutEnabled() bool {
	if d == nil {
		return false
	}
	return d.IdleTimeoutEnabled
}

func (d *DeploymentConfigV2) GetEnv() []DeploymentConfigV2Env {
	if d == nil {
		return []DeploymentConfigV2Env{}
	}
	return d.Env
}

func (d *DeploymentConfigV2) GetRoomsPerProcess() int {
	if d == nil {
		return 0
	}
	return d.RoomsPerProcess
}

func (d *DeploymentConfigV2) GetAdditionalContainerPorts() []ContainerPort {
	if d == nil {
		return nil
	}
	return d.AdditionalContainerPorts
}

func (d *DeploymentConfigV2) GetTransportType() TransportType {
	if d == nil {
		return TransportType("")
	}
	return d.TransportType
}

func (d *DeploymentConfigV2) GetContainerPort() int {
	if d == nil {
		return 0
	}
	return d.ContainerPort
}

func (d *DeploymentConfigV2) GetRequestedMemoryMB() float64 {
	if d == nil {
		return 0.0
	}
	return d.RequestedMemoryMB
}

func (d *DeploymentConfigV2) GetRequestedCPU() float64 {
	if d == nil {
		return 0.0
	}
	return d.RequestedCPU
}
