// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type DeploymentV3Env struct {
	Value string `json:"value"`
	Name  string `json:"name"`
}

func (d *DeploymentV3Env) GetValue() string {
	if d == nil {
		return ""
	}
	return d.Value
}

func (d *DeploymentV3Env) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type DeploymentV3 struct {
	// The id of the fleet.
	FleetID *string `json:"fleetId,omitempty"`
	// Arbitrary metadata associated with a deployment.
	DeploymentTag *string `json:"deploymentTag,omitempty"`
	// Option to shut down processes that have had no new connections or rooms
	// for five minutes.
	IdleTimeoutEnabled bool `json:"idleTimeoutEnabled"`
	// The environment variable that our process will have access to at runtime.
	Env []DeploymentV3Env `json:"env"`
	// Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
	RoomsPerProcess int `json:"roomsPerProcess"`
	// Additional ports your server listens on.
	AdditionalContainerPorts []ContainerPort `json:"additionalContainerPorts"`
	// A container port object represents the transport configruations for how your server will listen.
	DefaultContainerPort ContainerPort `json:"defaultContainerPort"`
	// When the deployment was created.
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
	// The number of GPUs allocated to your process. Must be an integer.
	// If not provided, the requested GPU is 0.
	RequestedGPU *float64 `json:"requestedGPU,omitempty"`
	// EXPERIMENTAL - this feature is in closed beta.
	// The number of GPUs allocated to your process. Must be an integer.
	// If not provided, the requested GPU is 0.
	ExperimentalRequestedGPU *float64 `json:"experimentalRequestedGPU,omitempty"`
	// The amount of memory allocated to your process. By default, this is capped
	// at 8192 MB, but can be increased further on the Enterprise tier.
	RequestedMemoryMB float64 `json:"requestedMemoryMB"`
	// The number of cores allocated to your process.
	RequestedCPU float64 `json:"requestedCPU"`
	// System generated id for a deployment.
	DeploymentID string `json:"deploymentId"`
	// Tag to associate an external version with a build. It is accessible via [`GetBuild()`](https://hathora.dev/api#tag/BuildsV3/operation/GetBuild).
	BuildTag *string `json:"buildTag,omitempty"`
	// System generated id for a build. Can also be user defined when creating a build.
	BuildID string `json:"buildId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
}

func (d DeploymentV3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeploymentV3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeploymentV3) GetFleetID() *string {
	if d == nil {
		return nil
	}
	return d.FleetID
}

func (d *DeploymentV3) GetDeploymentTag() *string {
	if d == nil {
		return nil
	}
	return d.DeploymentTag
}

func (d *DeploymentV3) GetIdleTimeoutEnabled() bool {
	if d == nil {
		return false
	}
	return d.IdleTimeoutEnabled
}

func (d *DeploymentV3) GetEnv() []DeploymentV3Env {
	if d == nil {
		return []DeploymentV3Env{}
	}
	return d.Env
}

func (d *DeploymentV3) GetRoomsPerProcess() int {
	if d == nil {
		return 0
	}
	return d.RoomsPerProcess
}

func (d *DeploymentV3) GetAdditionalContainerPorts() []ContainerPort {
	if d == nil {
		return []ContainerPort{}
	}
	return d.AdditionalContainerPorts
}

func (d *DeploymentV3) GetDefaultContainerPort() ContainerPort {
	if d == nil {
		return ContainerPort{}
	}
	return d.DefaultContainerPort
}

func (d *DeploymentV3) GetCreatedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.CreatedAt
}

func (d *DeploymentV3) GetCreatedBy() string {
	if d == nil {
		return ""
	}
	return d.CreatedBy
}

func (d *DeploymentV3) GetRequestedGPU() *float64 {
	if d == nil {
		return nil
	}
	return d.RequestedGPU
}

func (d *DeploymentV3) GetExperimentalRequestedGPU() *float64 {
	if d == nil {
		return nil
	}
	return d.ExperimentalRequestedGPU
}

func (d *DeploymentV3) GetRequestedMemoryMB() float64 {
	if d == nil {
		return 0.0
	}
	return d.RequestedMemoryMB
}

func (d *DeploymentV3) GetRequestedCPU() float64 {
	if d == nil {
		return 0.0
	}
	return d.RequestedCPU
}

func (d *DeploymentV3) GetDeploymentID() string {
	if d == nil {
		return ""
	}
	return d.DeploymentID
}

func (d *DeploymentV3) GetBuildTag() *string {
	if d == nil {
		return nil
	}
	return d.BuildTag
}

func (d *DeploymentV3) GetBuildID() string {
	if d == nil {
		return ""
	}
	return d.BuildID
}

func (d *DeploymentV3) GetAppID() string {
	if d == nil {
		return ""
	}
	return d.AppID
}
