// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeprecatedProcessMetricName string

const (
	DeprecatedProcessMetricNameCPU               DeprecatedProcessMetricName = "cpu"
	DeprecatedProcessMetricNameMemory            DeprecatedProcessMetricName = "memory"
	DeprecatedProcessMetricNameRateEgress        DeprecatedProcessMetricName = "rate_egress"
	DeprecatedProcessMetricNameTotalEgress       DeprecatedProcessMetricName = "total_egress"
	DeprecatedProcessMetricNameActiveConnections DeprecatedProcessMetricName = "active_connections"
)

func (e DeprecatedProcessMetricName) ToPointer() *DeprecatedProcessMetricName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeprecatedProcessMetricName) IsExact() bool {
	if e != nil {
		switch *e {
		case "cpu", "memory", "rate_egress", "total_egress", "active_connections":
			return true
		}
	}
	return false
}
