// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeprecatedProcessMetricsData struct {
	ActiveConnections []MetricValue `json:"active_connections,omitempty"`
	TotalEgress       []MetricValue `json:"total_egress,omitempty"`
	RateEgress        []MetricValue `json:"rate_egress,omitempty"`
	Memory            []MetricValue `json:"memory,omitempty"`
	CPU               []MetricValue `json:"cpu,omitempty"`
}

func (d *DeprecatedProcessMetricsData) GetActiveConnections() []MetricValue {
	if d == nil {
		return nil
	}
	return d.ActiveConnections
}

func (d *DeprecatedProcessMetricsData) GetTotalEgress() []MetricValue {
	if d == nil {
		return nil
	}
	return d.TotalEgress
}

func (d *DeprecatedProcessMetricsData) GetRateEgress() []MetricValue {
	if d == nil {
		return nil
	}
	return d.RateEgress
}

func (d *DeprecatedProcessMetricsData) GetMemory() []MetricValue {
	if d == nil {
		return nil
	}
	return d.Memory
}

func (d *DeprecatedProcessMetricsData) GetCPU() []MetricValue {
	if d == nil {
		return nil
	}
	return d.CPU
}
