// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type FleetErrorState struct {
	LastErrorTimestamp *time.Time `json:"lastErrorTimestamp"`
	LastErrorMessage   *string    `json:"lastErrorMessage"`
	LastErrorLogID     *string    `json:"lastErrorLogId"`
	InError            bool       `json:"inError"`
}

func (f FleetErrorState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FleetErrorState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FleetErrorState) GetLastErrorTimestamp() *time.Time {
	if f == nil {
		return nil
	}
	return f.LastErrorTimestamp
}

func (f *FleetErrorState) GetLastErrorMessage() *string {
	if f == nil {
		return nil
	}
	return f.LastErrorMessage
}

func (f *FleetErrorState) GetLastErrorLogID() *string {
	if f == nil {
		return nil
	}
	return f.LastErrorLogID
}

func (f *FleetErrorState) GetInError() bool {
	if f == nil {
		return false
	}
	return f.InError
}
