// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetRegionConfig struct {
	CloudMinVcpus int `json:"cloudMinVcpus"`
}

func (f *FleetRegionConfig) GetCloudMinVcpus() int {
	if f == nil {
		return 0
	}
	return f.CloudMinVcpus
}
