// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FleetMetricName - Represents the valid metric names available to measure/manage fleets in a given region
type FleetMetricName string

const (
	FleetMetricNameProvisionedTotal     FleetMetricName = "provisionedTotal"
	FleetMetricNameProvisionedBareMetal FleetMetricName = "provisionedBareMetal"
	FleetMetricNameProvisionedCloud     FleetMetricName = "provisionedCloud"
	FleetMetricNameUtilized             FleetMetricName = "utilized"
	FleetMetricNameSystemOverhead       FleetMetricName = "systemOverhead"
)

func (e FleetMetricName) ToPointer() *FleetMetricName {
	return &e
}
