// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FleetMetricName - Represents the valid metric names available to measure/manage fleets in a given region
type FleetMetricName string

const (
	FleetMetricNameProvisionedTotal     FleetMetricName = "provisionedTotal"
	FleetMetricNameProvisionedBareMetal FleetMetricName = "provisionedBareMetal"
	FleetMetricNameProvisionedCloud     FleetMetricName = "provisionedCloud"
	FleetMetricNameUtilized             FleetMetricName = "utilized"
	FleetMetricNameSystemOverhead       FleetMetricName = "systemOverhead"
)

func (e FleetMetricName) ToPointer() *FleetMetricName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FleetMetricName) IsExact() bool {
	if e != nil {
		switch *e {
		case "provisionedTotal", "provisionedBareMetal", "provisionedCloud", "utilized", "systemOverhead":
			return true
		}
	}
	return false
}
