// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetsPage struct {
	Fleets []Fleet `json:"fleets"`
}

func (f *FleetsPage) GetFleets() []Fleet {
	if f == nil {
		return []Fleet{}
	}
	return f.Fleets
}
