// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

// FleetRegion - A fleet region is a region in which a fleet can be deployed.
// You can update cloudMinVcpus once every five minutes. It must be a multiple of
// scaleIncrementVcpus
type FleetRegion struct {
	CloudMinVcpusUpdatedAt time.Time `json:"cloudMinVcpusUpdatedAt"`
	CloudMinVcpus          int       `json:"cloudMinVcpus"`
	// This field is deprecated and may contain the value -1. For node increment values, refer to nodeShape on the Fleet.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ScaleIncrementVcpus int `json:"scaleIncrementVcpus"`
}

func (f FleetRegion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FleetRegion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"cloudMinVcpusUpdatedAt", "cloudMinVcpus", "scaleIncrementVcpus"}); err != nil {
		return err
	}
	return nil
}

func (f *FleetRegion) GetCloudMinVcpusUpdatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CloudMinVcpusUpdatedAt
}

func (f *FleetRegion) GetCloudMinVcpus() int {
	if f == nil {
		return 0
	}
	return f.CloudMinVcpus
}

func (f *FleetRegion) GetScaleIncrementVcpus() int {
	if f == nil {
		return 0
	}
	return f.ScaleIncrementVcpus
}
