// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetMetricsData struct {
	SystemOverhead       []MetricValue `json:"systemOverhead,omitempty"`
	Utilized             []MetricValue `json:"utilized,omitempty"`
	ProvisionedCloud     []MetricValue `json:"provisionedCloud,omitempty"`
	ProvisionedBareMetal []MetricValue `json:"provisionedBareMetal,omitempty"`
	ProvisionedTotal     []MetricValue `json:"provisionedTotal,omitempty"`
}

func (f *FleetMetricsData) GetSystemOverhead() []MetricValue {
	if f == nil {
		return nil
	}
	return f.SystemOverhead
}

func (f *FleetMetricsData) GetUtilized() []MetricValue {
	if f == nil {
		return nil
	}
	return f.Utilized
}

func (f *FleetMetricsData) GetProvisionedCloud() []MetricValue {
	if f == nil {
		return nil
	}
	return f.ProvisionedCloud
}

func (f *FleetMetricsData) GetProvisionedBareMetal() []MetricValue {
	if f == nil {
		return nil
	}
	return f.ProvisionedBareMetal
}

func (f *FleetMetricsData) GetProvisionedTotal() []MetricValue {
	if f == nil {
		return nil
	}
	return f.ProvisionedTotal
}
