// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FleetRegionConfigV2 struct {
	// The minimum number of nodes that should be running.
	NodeBaseline int `json:"nodeBaseline"`
}

func (f *FleetRegionConfigV2) GetNodeBaseline() int {
	if f == nil {
		return 0
	}
	return f.NodeBaseline
}
