// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Fleet - A fleet is a collection of vCPUs across your regions that can scale up and down based on demand.
type Fleet struct {
	NodeShape        NodeShape         `json:"nodeShape"`
	AutoscalerConfig *AutoscalerConfig `json:"autoscalerConfig,omitempty"`
	// Readable name for a fleet. Must be unique within an organization.
	Name *string `json:"name,omitempty"`
	// System generated unique identifier for an organization. Not guaranteed to have a specific format.
	OrgID string `json:"orgId"`
	// The id of the fleet.
	FleetID string `json:"fleetId"`
}

func (f *Fleet) GetNodeShape() NodeShape {
	if f == nil {
		return NodeShape("")
	}
	return f.NodeShape
}

func (f *Fleet) GetAutoscalerConfig() *AutoscalerConfig {
	if f == nil {
		return nil
	}
	return f.AutoscalerConfig
}

func (f *Fleet) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *Fleet) GetOrgID() string {
	if f == nil {
		return ""
	}
	return f.OrgID
}

func (f *Fleet) GetFleetID() string {
	if f == nil {
		return ""
	}
	return f.FleetID
}
