// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Hosting string

const (
	HostingMetal  Hosting = "metal"
	HostingCloud  Hosting = "cloud"
	HostingShared Hosting = "shared"
)

func (e Hosting) ToPointer() *Hosting {
	return &e
}
