// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Hosting string

const (
	HostingMetal  Hosting = "metal"
	HostingCloud  Hosting = "cloud"
	HostingShared Hosting = "shared"
)

func (e Hosting) ToPointer() *Hosting {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Hosting) IsExact() bool {
	if e != nil {
		switch *e {
		case "metal", "cloud", "shared":
			return true
		}
	}
	return false
}
