// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type InvoiceStatus string

const (
	InvoiceStatusPending InvoiceStatus = "pending"
	InvoiceStatusPaid    InvoiceStatus = "paid"
	InvoiceStatusOverdue InvoiceStatus = "overdue"
)

func (e InvoiceStatus) ToPointer() *InvoiceStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoiceStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "paid", "overdue":
			return true
		}
	}
	return false
}
