// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type Invoice struct {
	Status    InvoiceStatus `json:"status"`
	AmountDue float64       `json:"amountDue"`
	PdfURL    string        `json:"pdfUrl"`
	DueDate   time.Time     `json:"dueDate"`
	Year      float64       `json:"year"`
	Month     float64       `json:"month"`
	ID        string        `json:"id"`
}

func (i Invoice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Invoice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"status", "amountDue", "pdfUrl", "dueDate", "year", "month", "id"}); err != nil {
		return err
	}
	return nil
}

func (i *Invoice) GetStatus() InvoiceStatus {
	if i == nil {
		return InvoiceStatus("")
	}
	return i.Status
}

func (i *Invoice) GetAmountDue() float64 {
	if i == nil {
		return 0.0
	}
	return i.AmountDue
}

func (i *Invoice) GetPdfURL() string {
	if i == nil {
		return ""
	}
	return i.PdfURL
}

func (i *Invoice) GetDueDate() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.DueDate
}

func (i *Invoice) GetYear() float64 {
	if i == nil {
		return 0.0
	}
	return i.Year
}

func (i *Invoice) GetMonth() float64 {
	if i == nil {
		return 0.0
	}
	return i.Month
}

func (i *Invoice) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}
