// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkPaymentMethod struct {
	Email *string `json:"email,omitempty"`
}

func (l *LinkPaymentMethod) GetEmail() *string {
	if l == nil {
		return nil
	}
	return l.Email
}
