// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LoadBalancerConfig struct {
	// Whether load balancing is enabled for this application.
	Enabled bool `json:"enabled"`
}

func (l *LoadBalancerConfig) GetEnabled() bool {
	if l == nil {
		return false
	}
	return l.Enabled
}
