// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LoadBalancerConfig struct {
	// Whether load balancing is enabled for this application.
	Enabled bool `json:"enabled"`
}

func (o *LoadBalancerConfig) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}
