// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NicknameObject struct {
	// An alias to represent a player.
	Nickname string `json:"nickname"`
}

func (n *NicknameObject) GetNickname() string {
	if n == nil {
		return ""
	}
	return n.Nickname
}
