// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeShapeID string

const (
	NodeShapeIDShapeAmd6448    NodeShapeID = "shape-amd64-4-8"
	NodeShapeIDShapeAmd64816   NodeShapeID = "shape-amd64-8-16"
	NodeShapeIDShapeAmd641632  NodeShapeID = "shape-amd64-16-32"
	NodeShapeIDShapeAmd643264  NodeShapeID = "shape-amd64-32-64"
	NodeShapeIDShapeAmd6464128 NodeShapeID = "shape-amd64-64-128"
	NodeShapeIDShapeAmd64416   NodeShapeID = "shape-amd64-4-16"
	NodeShapeIDShapeAmd64832   NodeShapeID = "shape-amd64-8-32"
	NodeShapeIDShapeAmd641664  NodeShapeID = "shape-amd64-16-64"
	NodeShapeIDShapeAmd6432128 NodeShapeID = "shape-amd64-32-128"
	NodeShapeIDShapeL414       NodeShapeID = "shape-l4-1-4"
	NodeShapeIDShapeL41        NodeShapeID = "shape-l4-1"
	NodeShapeIDShapeL42        NodeShapeID = "shape-l4-2"
	NodeShapeIDShapeL44        NodeShapeID = "shape-l4-4"
	NodeShapeIDShapeL48        NodeShapeID = "shape-l4-8"
	NodeShapeIDShapeH100pcie1  NodeShapeID = "shape-h100pcie-1"
	NodeShapeIDShapeH100pcie2  NodeShapeID = "shape-h100pcie-2"
	NodeShapeIDShapeH100pcie4  NodeShapeID = "shape-h100pcie-4"
	NodeShapeIDShapeH100pcie8  NodeShapeID = "shape-h100pcie-8"
	NodeShapeIDShapeH100sxm51  NodeShapeID = "shape-h100sxm5-1"
	NodeShapeIDShapeH100sxm58  NodeShapeID = "shape-h100sxm5-8"
	NodeShapeIDShapeH200sxm51  NodeShapeID = "shape-h200sxm5-1"
	NodeShapeIDShapeH200sxm58  NodeShapeID = "shape-h200sxm5-8"
)

func (e NodeShapeID) ToPointer() *NodeShapeID {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NodeShapeID) IsExact() bool {
	if e != nil {
		switch *e {
		case "shape-amd64-4-8", "shape-amd64-8-16", "shape-amd64-16-32", "shape-amd64-32-64", "shape-amd64-64-128", "shape-amd64-4-16", "shape-amd64-8-32", "shape-amd64-16-64", "shape-amd64-32-128", "shape-l4-1-4", "shape-l4-1", "shape-l4-2", "shape-l4-4", "shape-l4-8", "shape-h100pcie-1", "shape-h100pcie-2", "shape-h100pcie-4", "shape-h100pcie-8", "shape-h100sxm5-1", "shape-h100sxm5-8", "shape-h200sxm5-1", "shape-h200sxm5-8":
			return true
		}
	}
	return false
}
