// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeFamilyID string

const (
	NodeFamilyIDFamilyAmd6412  NodeFamilyID = "family-amd64-1-2"
	NodeFamilyIDFamilyAmd6414  NodeFamilyID = "family-amd64-1-4"
	NodeFamilyIDFamilyL414     NodeFamilyID = "family-l4-1-4"
	NodeFamilyIDFamilyL4112    NodeFamilyID = "family-l4-1-12"
	NodeFamilyIDFamilyH100pcie NodeFamilyID = "family-h100pcie"
	NodeFamilyIDFamilyH100sxm5 NodeFamilyID = "family-h100sxm5"
	NodeFamilyIDFamilyH200sxm5 NodeFamilyID = "family-h200sxm5"
)

func (e NodeFamilyID) ToPointer() *NodeFamilyID {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NodeFamilyID) IsExact() bool {
	if e != nil {
		switch *e {
		case "family-amd64-1-2", "family-amd64-1-4", "family-l4-1-4", "family-l4-1-12", "family-h100pcie", "family-h100sxm5", "family-h200sxm5":
			return true
		}
	}
	return false
}
