// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeShape string

const (
	NodeShapeCpu48           NodeShape = "cpu-4-8"
	NodeShapeCpu816          NodeShape = "cpu-8-16"
	NodeShapeCpu1632         NodeShape = "cpu-16-32"
	NodeShapeCpu3264         NodeShape = "cpu-32-64"
	NodeShapeCpu64128        NodeShape = "cpu-64-128"
	NodeShapeCpu416          NodeShape = "cpu-4-16"
	NodeShapeCpu832          NodeShape = "cpu-8-32"
	NodeShapeCpu1664         NodeShape = "cpu-16-64"
	NodeShapeCpu32128        NodeShape = "cpu-32-128"
	NodeShapeGpuL41416       NodeShape = "gpu-l4-1-4-16"
	NodeShapeGpuL411248      NodeShape = "gpu-l4-1-12-48"
	NodeShapeGpuL422496      NodeShape = "gpu-l4-2-24-96"
	NodeShapeGpuL4448192     NodeShape = "gpu-l4-4-48-192"
	NodeShapeGpuL4896384     NodeShape = "gpu-l4-8-96-384"
	NodeShapeGpuH100126234   NodeShape = "gpu-h100-1-26-234"
	NodeShapeGpuH100252468   NodeShape = "gpu-h100-2-52-468"
	NodeShapeGpuH1004104936  NodeShape = "gpu-h100-4-104-936"
	NodeShapeGpuH10082081872 NodeShape = "gpu-h100-8-208-1872"
	NodeShapeGpuH100128180   NodeShape = "gpu-h100-1-28-180"
	NodeShapeGpuH100260360   NodeShape = "gpu-h100-2-60-360"
	NodeShapeGpuH1004124720  NodeShape = "gpu-h100-4-124-720"
	NodeShapeGpuH10082521440 NodeShape = "gpu-h100-8-252-1440"
)

func (e NodeShape) ToPointer() *NodeShape {
	return &e
}
