// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OrgTokenStatus string

const (
	OrgTokenStatusActive  OrgTokenStatus = "active"
	OrgTokenStatusRevoked OrgTokenStatus = "revoked"
)

func (e OrgTokenStatus) ToPointer() *OrgTokenStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrgTokenStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "revoked":
			return true
		}
	}
	return false
}
