// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PartialAppConfigWithServiceConfig - Make all properties in T optional
type PartialAppConfigWithServiceConfig struct {
	AppName *string `json:"appName,omitempty"`
	// Configure [player authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
	AuthConfiguration *AuthConfiguration `json:"authConfiguration,omitempty"`
	ServiceConfig     *ServiceConfig     `json:"serviceConfig,omitempty"`
}

func (o *PartialAppConfigWithServiceConfig) GetAppName() *string {
	if o == nil {
		return nil
	}
	return o.AppName
}

func (o *PartialAppConfigWithServiceConfig) GetAuthConfiguration() *AuthConfiguration {
	if o == nil {
		return nil
	}
	return o.AuthConfiguration
}

func (o *PartialAppConfigWithServiceConfig) GetServiceConfig() *ServiceConfig {
	if o == nil {
		return nil
	}
	return o.ServiceConfig
}
