// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PartialAppConfigWithServiceConfig - Make all properties in T optional
type PartialAppConfigWithServiceConfig struct {
	AppName *string `json:"appName,omitempty"`
	// Configure [player authentication](https://hathora.dev/docs/backend-integrations/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
	AuthConfiguration *AuthConfiguration  `json:"authConfiguration,omitempty"`
	ServiceConfig     *ServiceConfigWrite `json:"serviceConfig,omitempty"`
}

func (p *PartialAppConfigWithServiceConfig) GetAppName() *string {
	if p == nil {
		return nil
	}
	return p.AppName
}

func (p *PartialAppConfigWithServiceConfig) GetAuthConfiguration() *AuthConfiguration {
	if p == nil {
		return nil
	}
	return p.AuthConfiguration
}

func (p *PartialAppConfigWithServiceConfig) GetServiceConfig() *ServiceConfigWrite {
	if p == nil {
		return nil
	}
	return p.ServiceConfig
}
