// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentMethod - Make all properties in T optional
type PaymentMethod struct {
	Card *CardPaymentMethod `json:"card,omitempty"`
	Ach  *AchPaymentMethod  `json:"ach,omitempty"`
	Link *LinkPaymentMethod `json:"link,omitempty"`
}

func (p *PaymentMethod) GetCard() *CardPaymentMethod {
	if p == nil {
		return nil
	}
	return p.Card
}

func (p *PaymentMethod) GetAch() *AchPaymentMethod {
	if p == nil {
		return nil
	}
	return p.Ach
}

func (p *PaymentMethod) GetLink() *LinkPaymentMethod {
	if p == nil {
		return nil
	}
	return p.Link
}
