// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PendingOrgInvitesPage struct {
	Invites []PendingOrgInvite `json:"invites"`
}

func (p *PendingOrgInvitesPage) GetInvites() []PendingOrgInvite {
	if p == nil {
		return []PendingOrgInvite{}
	}
	return p.Invites
}
