// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

type PendingOrgInviteScopesType string

const (
	PendingOrgInviteScopesTypeUserRole     PendingOrgInviteScopesType = "UserRole"
	PendingOrgInviteScopesTypeArrayOfScope PendingOrgInviteScopesType = "arrayOfScope"
)

type PendingOrgInviteScopes struct {
	UserRole     *UserRole `queryParam:"inline" union:"member"`
	ArrayOfScope []Scope   `queryParam:"inline" union:"member"`

	Type PendingOrgInviteScopesType
}

func CreatePendingOrgInviteScopesUserRole(userRole UserRole) PendingOrgInviteScopes {
	typ := PendingOrgInviteScopesTypeUserRole

	return PendingOrgInviteScopes{
		UserRole: &userRole,
		Type:     typ,
	}
}

func CreatePendingOrgInviteScopesArrayOfScope(arrayOfScope []Scope) PendingOrgInviteScopes {
	typ := PendingOrgInviteScopesTypeArrayOfScope

	return PendingOrgInviteScopes{
		ArrayOfScope: arrayOfScope,
		Type:         typ,
	}
}

func (u *PendingOrgInviteScopes) UnmarshalJSON(data []byte) error {

	var userRole UserRole = UserRole("")
	if err := utils.UnmarshalJSON(data, &userRole, "", true, nil); err == nil {
		u.UserRole = &userRole
		u.Type = PendingOrgInviteScopesTypeUserRole
		return nil
	}

	var arrayOfScope []Scope = []Scope{}
	if err := utils.UnmarshalJSON(data, &arrayOfScope, "", true, nil); err == nil {
		u.ArrayOfScope = arrayOfScope
		u.Type = PendingOrgInviteScopesTypeArrayOfScope
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PendingOrgInviteScopes", string(data))
}

func (u PendingOrgInviteScopes) MarshalJSON() ([]byte, error) {
	if u.UserRole != nil {
		return utils.MarshalJSON(u.UserRole, "", true)
	}

	if u.ArrayOfScope != nil {
		return utils.MarshalJSON(u.ArrayOfScope, "", true)
	}

	return nil, errors.New("could not marshal union type PendingOrgInviteScopes: all fields are null")
}

type PendingOrgInvite struct {
	Scopes    PendingOrgInviteScopes `json:"scopes"`
	CreatedAt time.Time              `json:"createdAt"`
	InvitedBy string                 `json:"invitedBy"`
	// A user's email.
	UserEmail string `json:"userEmail"`
	// System generated unique identifier for an organization. Not guaranteed to have a specific format.
	OrgID string `json:"orgId"`
}

func (p PendingOrgInvite) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendingOrgInvite) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendingOrgInvite) GetScopes() PendingOrgInviteScopes {
	if p == nil {
		return PendingOrgInviteScopes{}
	}
	return p.Scopes
}

func (p *PendingOrgInvite) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PendingOrgInvite) GetInvitedBy() string {
	if p == nil {
		return ""
	}
	return p.InvitedBy
}

func (p *PendingOrgInvite) GetUserEmail() string {
	if p == nil {
		return ""
	}
	return p.UserEmail
}

func (p *PendingOrgInvite) GetOrgID() string {
	if p == nil {
		return ""
	}
	return p.OrgID
}
