// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PingEndpoints struct {
	Port   float64 `json:"port"`
	Host   string  `json:"host"`
	Region Region  `json:"region"`
}

func (p *PingEndpoints) GetPort() float64 {
	if p == nil {
		return 0.0
	}
	return p.Port
}

func (p *PingEndpoints) GetHost() string {
	if p == nil {
		return ""
	}
	return p.Host
}

func (p *PingEndpoints) GetRegion() Region {
	if p == nil {
		return Region("")
	}
	return p.Region
}
