// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlayerTokenObject struct {
	// A unique Hathora-signed JWT player token.
	Token string `json:"token"`
}

func (p *PlayerTokenObject) GetToken() string {
	if p == nil {
		return ""
	}
	return p.Token
}
