// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

// ProcessWithRoomsExposedPort - Connection details for an active process.
type ProcessWithRoomsExposedPort struct {
	// Transport type specifies the underlying communication protocol to the exposed port.
	TransportType TransportType `json:"transportType"`
	Port          int           `json:"port"`
	Host          string        `json:"host"`
	Name          string        `json:"name"`
}

func (p *ProcessWithRoomsExposedPort) GetTransportType() TransportType {
	if p == nil {
		return TransportType("")
	}
	return p.TransportType
}

func (p *ProcessWithRoomsExposedPort) GetPort() int {
	if p == nil {
		return 0
	}
	return p.Port
}

func (p *ProcessWithRoomsExposedPort) GetHost() string {
	if p == nil {
		return ""
	}
	return p.Host
}

func (p *ProcessWithRoomsExposedPort) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

// ProcessWithRooms - A process object represents a runtime instance of your game server and its metadata.
type ProcessWithRooms struct {
	// Measures network traffic leaving the process in bytes.
	EgressedBytes int `json:"egressedBytes"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	IdleSince *time.Time `json:"idleSince"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ActiveConnectionsUpdatedAt time.Time `json:"activeConnectionsUpdatedAt"`
	// Tracks the number of active connections to a process.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ActiveConnections       int       `json:"activeConnections"`
	RoomsAllocatedUpdatedAt time.Time `json:"roomsAllocatedUpdatedAt"`
	// Tracks the number of rooms that have been allocated to the process.
	RoomsAllocated int `json:"roomsAllocated"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RoomSlotsAvailableUpdatedAt time.Time `json:"roomSlotsAvailableUpdatedAt"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	RoomSlotsAvailable float64 `json:"roomSlotsAvailable"`
	// Process in drain will not accept any new rooms.
	Draining bool `json:"draining"`
	// When the process has been terminated.
	TerminatedAt *time.Time `json:"terminatedAt"`
	// When the process is issued to stop. We use this to determine when we should stop billing.
	StoppingAt *time.Time `json:"stoppingAt"`
	// When the process bound to the specified port. We use this to determine when we should start billing.
	StartedAt *time.Time `json:"startedAt"`
	// When the process started being provisioned.
	StartingAt time.Time `json:"startingAt"`
	// Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
	RoomsPerProcess        int                          `json:"roomsPerProcess"`
	AdditionalExposedPorts []ExposedPort                `json:"additionalExposedPorts"`
	ExposedPort            *ProcessWithRoomsExposedPort `json:"exposedPort"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Port float64 `json:"port"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Host   string `json:"host"`
	Region Region `json:"region"`
	// System generated unique identifier to a runtime instance of your game server.
	ProcessID string `json:"processId"`
	// System generated id for a deployment. Increments by 1.
	DeploymentID int `json:"deploymentId"`
	// System generated unique identifier for an application.
	AppID      string                   `json:"appId"`
	Rooms      []RoomWithoutAllocations `json:"rooms"`
	TotalRooms int                      `json:"totalRooms"`
}

func (p ProcessWithRooms) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProcessWithRooms) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"egressedBytes", "activeConnectionsUpdatedAt", "activeConnections", "roomsAllocatedUpdatedAt", "roomsAllocated", "roomSlotsAvailableUpdatedAt", "roomSlotsAvailable", "draining", "startingAt", "roomsPerProcess", "additionalExposedPorts", "port", "host", "region", "processId", "deploymentId", "appId", "rooms", "totalRooms"}); err != nil {
		return err
	}
	return nil
}

func (p *ProcessWithRooms) GetEgressedBytes() int {
	if p == nil {
		return 0
	}
	return p.EgressedBytes
}

func (p *ProcessWithRooms) GetIdleSince() *time.Time {
	if p == nil {
		return nil
	}
	return p.IdleSince
}

func (p *ProcessWithRooms) GetActiveConnectionsUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.ActiveConnectionsUpdatedAt
}

func (p *ProcessWithRooms) GetActiveConnections() int {
	if p == nil {
		return 0
	}
	return p.ActiveConnections
}

func (p *ProcessWithRooms) GetRoomsAllocatedUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.RoomsAllocatedUpdatedAt
}

func (p *ProcessWithRooms) GetRoomsAllocated() int {
	if p == nil {
		return 0
	}
	return p.RoomsAllocated
}

func (p *ProcessWithRooms) GetRoomSlotsAvailableUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.RoomSlotsAvailableUpdatedAt
}

func (p *ProcessWithRooms) GetRoomSlotsAvailable() float64 {
	if p == nil {
		return 0.0
	}
	return p.RoomSlotsAvailable
}

func (p *ProcessWithRooms) GetDraining() bool {
	if p == nil {
		return false
	}
	return p.Draining
}

func (p *ProcessWithRooms) GetTerminatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.TerminatedAt
}

func (p *ProcessWithRooms) GetStoppingAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.StoppingAt
}

func (p *ProcessWithRooms) GetStartedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.StartedAt
}

func (p *ProcessWithRooms) GetStartingAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.StartingAt
}

func (p *ProcessWithRooms) GetRoomsPerProcess() int {
	if p == nil {
		return 0
	}
	return p.RoomsPerProcess
}

func (p *ProcessWithRooms) GetAdditionalExposedPorts() []ExposedPort {
	if p == nil {
		return []ExposedPort{}
	}
	return p.AdditionalExposedPorts
}

func (p *ProcessWithRooms) GetExposedPort() *ProcessWithRoomsExposedPort {
	if p == nil {
		return nil
	}
	return p.ExposedPort
}

func (p *ProcessWithRooms) GetPort() float64 {
	if p == nil {
		return 0.0
	}
	return p.Port
}

func (p *ProcessWithRooms) GetHost() string {
	if p == nil {
		return ""
	}
	return p.Host
}

func (p *ProcessWithRooms) GetRegion() Region {
	if p == nil {
		return Region("")
	}
	return p.Region
}

func (p *ProcessWithRooms) GetProcessID() string {
	if p == nil {
		return ""
	}
	return p.ProcessID
}

func (p *ProcessWithRooms) GetDeploymentID() int {
	if p == nil {
		return 0
	}
	return p.DeploymentID
}

func (p *ProcessWithRooms) GetAppID() string {
	if p == nil {
		return ""
	}
	return p.AppID
}

func (p *ProcessWithRooms) GetRooms() []RoomWithoutAllocations {
	if p == nil {
		return []RoomWithoutAllocations{}
	}
	return p.Rooms
}

func (p *ProcessWithRooms) GetTotalRooms() int {
	if p == nil {
		return 0
	}
	return p.TotalRooms
}
