// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProcessMetricName - Available metrics to query over time.
type ProcessMetricName string

const (
	ProcessMetricNameCPU               ProcessMetricName = "cpu"
	ProcessMetricNameMemory            ProcessMetricName = "memory"
	ProcessMetricNameRateEgress        ProcessMetricName = "rateEgress"
	ProcessMetricNameTotalEgress       ProcessMetricName = "totalEgress"
	ProcessMetricNameActiveConnections ProcessMetricName = "activeConnections"
	ProcessMetricNameGpuMemory         ProcessMetricName = "gpuMemory"
	ProcessMetricNameGpuUtilization    ProcessMetricName = "gpuUtilization"
)

func (e ProcessMetricName) ToPointer() *ProcessMetricName {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProcessMetricName) IsExact() bool {
	if e != nil {
		switch *e {
		case "cpu", "memory", "rateEgress", "totalEgress", "activeConnections", "gpuMemory", "gpuUtilization":
			return true
		}
	}
	return false
}
