// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProcessStatus string

const (
	ProcessStatusStarting ProcessStatus = "starting"
	ProcessStatusRunning  ProcessStatus = "running"
	ProcessStatusDraining ProcessStatus = "draining"
	ProcessStatusStopping ProcessStatus = "stopping"
	ProcessStatusStopped  ProcessStatus = "stopped"
	ProcessStatusFailed   ProcessStatus = "failed"
)

func (e ProcessStatus) ToPointer() *ProcessStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProcessStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "starting", "running", "draining", "stopping", "stopped", "failed":
			return true
		}
	}
	return false
}
