// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProcessMetricsData struct {
	ActiveConnections []MetricValue `json:"activeConnections,omitempty"`
	TotalEgress       []MetricValue `json:"totalEgress,omitempty"`
	RateEgress        []MetricValue `json:"rateEgress,omitempty"`
	Memory            []MetricValue `json:"memory,omitempty"`
	CPU               []MetricValue `json:"cpu,omitempty"`
}

func (p *ProcessMetricsData) GetActiveConnections() []MetricValue {
	if p == nil {
		return nil
	}
	return p.ActiveConnections
}

func (p *ProcessMetricsData) GetTotalEgress() []MetricValue {
	if p == nil {
		return nil
	}
	return p.TotalEgress
}

func (p *ProcessMetricsData) GetRateEgress() []MetricValue {
	if p == nil {
		return nil
	}
	return p.RateEgress
}

func (p *ProcessMetricsData) GetMemory() []MetricValue {
	if p == nil {
		return nil
	}
	return p.Memory
}

func (p *ProcessMetricsData) GetCPU() []MetricValue {
	if p == nil {
		return nil
	}
	return p.CPU
}
