// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProcessAutoscalerConfig - The configuration for the Process Autoscaler for this application.
// Autoscaling must be enabled on a per-region basis.
// EXPERIMENTAL - This feature is in closed beta.
type ProcessAutoscalerConfig struct {
	TargetMetric AutoscalerTargetMetric `json:"targetMetric"`
}

func (o *ProcessAutoscalerConfig) GetTargetMetric() AutoscalerTargetMetric {
	if o == nil {
		return AutoscalerTargetMetric{}
	}
	return o.TargetMetric
}
