// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegistryConfig struct {
	Auth        *string `json:"auth,omitempty"`
	RegistryURL *string `json:"registryUrl,omitempty"`
	Image       string  `json:"image"`
}

func (r *RegistryConfig) GetAuth() *string {
	if r == nil {
		return nil
	}
	return r.Auth
}

func (r *RegistryConfig) GetRegistryURL() *string {
	if r == nil {
		return nil
	}
	return r.RegistryURL
}

func (r *RegistryConfig) GetImage() string {
	if r == nil {
		return ""
	}
	return r.Image
}
