// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegistryConfig struct {
	Auth        *string `json:"auth,omitempty"`
	RegistryURL *string `json:"registryUrl,omitempty"`
	Image       string  `json:"image"`
}

func (o *RegistryConfig) GetAuth() *string {
	if o == nil {
		return nil
	}
	return o.Auth
}

func (o *RegistryConfig) GetRegistryURL() *string {
	if o == nil {
		return nil
	}
	return o.RegistryURL
}

func (o *RegistryConfig) GetImage() string {
	if o == nil {
		return ""
	}
	return o.Image
}
