// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RescindUserInvite struct {
	// A user's email.
	UserEmail string `json:"userEmail"`
}

func (r *RescindUserInvite) GetUserEmail() string {
	if r == nil {
		return ""
	}
	return r.UserEmail
}
