// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

// RoomWithoutAllocationsCurrentAllocation - Metadata on an allocated instance of a room.
type RoomWithoutAllocationsCurrentAllocation struct {
	UnscheduledAt *time.Time `json:"unscheduledAt"`
	ScheduledAt   time.Time  `json:"scheduledAt"`
	// System generated unique identifier to a runtime instance of your game server.
	ProcessID string `json:"processId"`
	// System generated unique identifier to an allocated instance of a room.
	RoomAllocationID string `json:"roomAllocationId"`
}

func (r RoomWithoutAllocationsCurrentAllocation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoomWithoutAllocationsCurrentAllocation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RoomWithoutAllocationsCurrentAllocation) GetUnscheduledAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UnscheduledAt
}

func (r *RoomWithoutAllocationsCurrentAllocation) GetScheduledAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ScheduledAt
}

func (r *RoomWithoutAllocationsCurrentAllocation) GetProcessID() string {
	if r == nil {
		return ""
	}
	return r.ProcessID
}

func (r *RoomWithoutAllocationsCurrentAllocation) GetRoomAllocationID() string {
	if r == nil {
		return ""
	}
	return r.RoomAllocationID
}

type RoomWithoutAllocations struct {
	CurrentAllocation *RoomWithoutAllocationsCurrentAllocation `json:"currentAllocation"`
	// The allocation status of a room.
	//
	// `scheduling`: a process is not allocated yet and the room is waiting to be scheduled
	//
	// `active`: ready to accept connections
	//
	// `destroyed`: all associated metadata is deleted
	Status     RoomStatus `json:"status"`
	RoomConfig *string    `json:"roomConfig,omitempty"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
	// System generated unique identifier for an application.
	AppID string `json:"appId"`
}

func (r *RoomWithoutAllocations) GetCurrentAllocation() *RoomWithoutAllocationsCurrentAllocation {
	if r == nil {
		return nil
	}
	return r.CurrentAllocation
}

func (r *RoomWithoutAllocations) GetStatus() RoomStatus {
	if r == nil {
		return RoomStatus("")
	}
	return r.Status
}

func (r *RoomWithoutAllocations) GetRoomConfig() *string {
	if r == nil {
		return nil
	}
	return r.RoomConfig
}

func (r *RoomWithoutAllocations) GetRoomID() string {
	if r == nil {
		return ""
	}
	return r.RoomID
}

func (r *RoomWithoutAllocations) GetAppID() string {
	if r == nil {
		return ""
	}
	return r.AppID
}
