// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RoomAllocationData - Connection information for the default and additional ports.
type RoomAllocationData struct {
	AdditionalExposedPorts []ExposedPort `json:"additionalExposedPorts"`
	// Connection details for an active process.
	ExposedPort *ExposedPort    `json:"exposedPort,omitempty"`
	Status      RoomReadyStatus `json:"status"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
	// System generated unique identifier to a runtime instance of your game server.
	ProcessID *string `json:"processId,omitempty"`
}

func (r *RoomAllocationData) GetAdditionalExposedPorts() []ExposedPort {
	if r == nil {
		return []ExposedPort{}
	}
	return r.AdditionalExposedPorts
}

func (r *RoomAllocationData) GetExposedPort() *ExposedPort {
	if r == nil {
		return nil
	}
	return r.ExposedPort
}

func (r *RoomAllocationData) GetStatus() RoomReadyStatus {
	if r == nil {
		return RoomReadyStatus("")
	}
	return r.Status
}

func (r *RoomAllocationData) GetRoomID() string {
	if r == nil {
		return ""
	}
	return r.RoomID
}

func (r *RoomAllocationData) GetProcessID() *string {
	if r == nil {
		return nil
	}
	return r.ProcessID
}
