// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RoomReadyStatus string

const (
	RoomReadyStatusActive   RoomReadyStatus = "active"
	RoomReadyStatusStarting RoomReadyStatus = "starting"
)

func (e RoomReadyStatus) ToPointer() *RoomReadyStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RoomReadyStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "starting":
			return true
		}
	}
	return false
}
