// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"time"
)

// RoomAllocation - Metadata on an allocated instance of a room.
type RoomAllocation struct {
	UnscheduledAt *time.Time `json:"unscheduledAt"`
	ScheduledAt   time.Time  `json:"scheduledAt"`
	// System generated unique identifier to a runtime instance of your game server.
	ProcessID string `json:"processId"`
	// System generated unique identifier to an allocated instance of a room.
	RoomAllocationID string `json:"roomAllocationId"`
}

func (r RoomAllocation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RoomAllocation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"scheduledAt", "processId", "roomAllocationId"}); err != nil {
		return err
	}
	return nil
}

func (r *RoomAllocation) GetUnscheduledAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.UnscheduledAt
}

func (r *RoomAllocation) GetScheduledAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ScheduledAt
}

func (r *RoomAllocation) GetProcessID() string {
	if r == nil {
		return ""
	}
	return r.ProcessID
}

func (r *RoomAllocation) GetRoomAllocationID() string {
	if r == nil {
		return ""
	}
	return r.RoomAllocationID
}
