// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Scope string

const (
	ScopeBillingReadWrite      Scope = "billing:read-write"
	ScopeBuildsRead            Scope = "builds:read"
	ScopeBuildsReadWrite       Scope = "builds:read-write"
	ScopeDeploymentsRead       Scope = "deployments:read"
	ScopeDeploymentsReadWrite  Scope = "deployments:read-write"
	ScopeApplicationsRead      Scope = "applications:read"
	ScopeApplicationsReadWrite Scope = "applications:read-write"
	ScopeProcessesRead         Scope = "processes:read"
	ScopeProcessesReadWrite    Scope = "processes:read-write"
	ScopeFleetsRead            Scope = "fleets:read"
	ScopeFleetsReadWrite       Scope = "fleets:read-write"
	ScopeOrgsRead              Scope = "orgs:read"
	ScopeOrgsReadWrite         Scope = "orgs:read-write"
	ScopeTokensRead            Scope = "tokens:read"
	ScopeTokensReadWrite       Scope = "tokens:read-write"
	ScopeTicketsRead           Scope = "tickets:read"
	ScopeTicketsReadWrite      Scope = "tickets:read-write"
	ScopeLoadBalancerAccess    Scope = "load-balancer:access"
)

func (e Scope) ToPointer() *Scope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Scope) IsExact() bool {
	if e != nil {
		switch *e {
		case "billing:read-write", "builds:read", "builds:read-write", "deployments:read", "deployments:read-write", "applications:read", "applications:read-write", "processes:read", "processes:read-write", "fleets:read", "fleets:read-write", "orgs:read", "orgs:read-write", "tokens:read", "tokens:read-write", "tickets:read", "tickets:read-write", "load-balancer:access":
			return true
		}
	}
	return false
}
