// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	HathoraDevToken *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (s *Security) GetHathoraDevToken() *string {
	if s == nil {
		return nil
	}
	return s.HathoraDevToken
}
