// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ServiceConfigWrite struct {
	// The configuration for the Process Autoscaler for this application.
	// Autoscaling must be enabled on a per-region basis.
	// EXPERIMENTAL - This feature is in closed beta.
	ProcessAutoscalerConfig *ProcessAutoscalerConfig             `json:"processAutoscalerConfig,omitempty"`
	LoadBalancer            *LoadBalancerConfig                  `json:"loadBalancer,omitempty"`
	StaticProcessAllocation []StaticProcessAllocationConfigWrite `json:"staticProcessAllocation"`
}

func (o *ServiceConfigWrite) GetProcessAutoscalerConfig() *ProcessAutoscalerConfig {
	if o == nil {
		return nil
	}
	return o.ProcessAutoscalerConfig
}

func (o *ServiceConfigWrite) GetLoadBalancer() *LoadBalancerConfig {
	if o == nil {
		return nil
	}
	return o.LoadBalancer
}

func (o *ServiceConfigWrite) GetStaticProcessAllocation() []StaticProcessAllocationConfigWrite {
	if o == nil {
		return []StaticProcessAllocationConfigWrite{}
	}
	return o.StaticProcessAllocation
}
