// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SetLobbyStateParams struct {
	// JSON blob to store metadata for a room. Must be smaller than 1MB.
	State any `json:"state"`
}

func (s *SetLobbyStateParams) GetState() any {
	if s == nil {
		return nil
	}
	return s.State
}
