// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
)

type Status string

const (
	StatusStarting Status = "starting"
)

func (e Status) ToPointer() *Status {
	return &e
}

type StartingConnectionInfo struct {
	Status Status `json:"status"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
}

func (s StartingConnectionInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartingConnectionInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"status", "roomId"}); err != nil {
		return err
	}
	return nil
}

func (o *StartingConnectionInfo) GetStatus() Status {
	if o == nil {
		return Status("")
	}
	return o.Status
}

func (o *StartingConnectionInfo) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}
