// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
)

type Status string

const (
	StatusStarting Status = "starting"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "starting":
			return true
		}
	}
	return false
}

type StartingConnectionInfo struct {
	Status Status `json:"status"`
	// Unique identifier to a game session or match. Use the default system generated ID or overwrite it with your own.
	// Note: error will be returned if `roomId` is not globally unique.
	RoomID string `json:"roomId"`
}

func (s StartingConnectionInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartingConnectionInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"status", "roomId"}); err != nil {
		return err
	}
	return nil
}

func (s *StartingConnectionInfo) GetStatus() Status {
	if s == nil {
		return Status("")
	}
	return s.Status
}

func (s *StartingConnectionInfo) GetRoomID() string {
	if s == nil {
		return ""
	}
	return s.RoomID
}
