// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StaticProcessAllocationConfig struct {
	// Whether autoscaling is enabled in this region. When enabled, `targetProcesses` is managed by the Process Autoscaler
	// in accordance with the `processAutoscalerConfig` field set on the application's `serviceConfig`.
	AutoscalingEnabled *bool `json:"autoscalingEnabled,omitempty"`
	// The maximum number of running processes.
	// Invariant: minProcesses <= maxProcesses
	MaxProcesses int `json:"maxProcesses"`
	// The target number of running processes
	// When autoscaling is enabled, this field is managed by the Process Autoscaler
	TargetProcesses int `json:"targetProcesses"`
	// The minimum number of running processes.
	// Invariant: 0 <= minProcesses < targetProcesses
	MinProcesses int    `json:"minProcesses"`
	Region       Region `json:"region"`
}

func (s *StaticProcessAllocationConfig) GetAutoscalingEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.AutoscalingEnabled
}

func (s *StaticProcessAllocationConfig) GetMaxProcesses() int {
	if s == nil {
		return 0
	}
	return s.MaxProcesses
}

func (s *StaticProcessAllocationConfig) GetTargetProcesses() int {
	if s == nil {
		return 0
	}
	return s.TargetProcesses
}

func (s *StaticProcessAllocationConfig) GetMinProcesses() int {
	if s == nil {
		return 0
	}
	return s.MinProcesses
}

func (s *StaticProcessAllocationConfig) GetRegion() Region {
	if s == nil {
		return Region("")
	}
	return s.Region
}
