// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransportType - Transport type specifies the underlying communication protocol to the exposed port.
type TransportType string

const (
	TransportTypeTCP TransportType = "tcp"
	TransportTypeUDP TransportType = "udp"
	TransportTypeTLS TransportType = "tls"
)

func (e TransportType) ToPointer() *TransportType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TransportType) IsExact() bool {
	if e != nil {
		switch *e {
		case "tcp", "udp", "tls":
			return true
		}
	}
	return false
}
