// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateFleet struct {
	NodeShape        *NodeShape       `json:"nodeShape,omitempty"`
	AutoscalerConfig AutoscalerConfig `json:"autoscalerConfig"`
}

func (o *UpdateFleet) GetNodeShape() *NodeShape {
	if o == nil {
		return nil
	}
	return o.NodeShape
}

func (o *UpdateFleet) GetAutoscalerConfig() AutoscalerConfig {
	if o == nil {
		return AutoscalerConfig{}
	}
	return o.AutoscalerConfig
}
