// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateRoomConfigParams struct {
	// Optional configuration parameters for the room. Can be any string including stringified JSON. It is accessible from the room via [`GetRoomInfo()`](https://hathora.dev/api#tag/RoomV2/operation/GetRoomInfo).
	RoomConfig string `json:"roomConfig"`
}

func (u *UpdateRoomConfigParams) GetRoomConfig() string {
	if u == nil {
		return ""
	}
	return u.RoomConfig
}
