// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateFleet struct {
	AutoscalerConfig AutoscalerConfig `json:"autoscalerConfig"`
}

func (o *UpdateFleet) GetAutoscalerConfig() AutoscalerConfig {
	if o == nil {
		return AutoscalerConfig{}
	}
	return o.AutoscalerConfig
}
