// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateFleet struct {
	NodeShape        *NodeShape       `json:"nodeShape,omitempty"`
	AutoscalerConfig AutoscalerConfig `json:"autoscalerConfig"`
}

func (u *UpdateFleet) GetNodeShape() *NodeShape {
	if u == nil {
		return nil
	}
	return u.NodeShape
}

func (u *UpdateFleet) GetAutoscalerConfig() AutoscalerConfig {
	if u == nil {
		return AutoscalerConfig{}
	}
	return u.AutoscalerConfig
}
