// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleViewer UserRole = "viewer"
)

func (e UserRole) ToPointer() *UserRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "admin", "member", "viewer":
			return true
		}
	}
	return false
}
