// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerificationEmailSuccess string

const (
	VerificationEmailSuccessSuccess VerificationEmailSuccess = "success"
)

func (e VerificationEmailSuccess) ToPointer() *VerificationEmailSuccess {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *VerificationEmailSuccess) IsExact() bool {
	if e != nil {
		switch *e {
		case "success":
			return true
		}
	}
	return false
}
