// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerificationEmailRequest struct {
	UserID string `json:"userId"`
}

func (v *VerificationEmailRequest) GetUserID() string {
	if v == nil {
		return ""
	}
	return v.UserID
}
