// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *Globals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

func (g *Globals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
