workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    HathoraCloud-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/hathora/hathora/my-source:main
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/hathora/hathora/hathora-cloud-oas
targets:
    hathora-cloud:
        target: go
        source: HathoraCloud-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hathora/hathora/hathora-cloud-oas-go-code-samples
            blocking: false
