// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type AcceptInviteRequest struct {
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

func (a *AcceptInviteRequest) GetOrgID() string {
	if a == nil {
		return ""
	}
	return a.OrgID
}
