// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateFleetDeprecatedGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (c *CreateFleetDeprecatedGlobals) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

type CreateFleetDeprecatedRequest struct {
	OrgID       *string                `queryParam:"style=form,explode=true,name=orgId"`
	CreateFleet components.CreateFleet `request:"mediaType=application/json"`
}

func (c *CreateFleetDeprecatedRequest) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *CreateFleetDeprecatedRequest) GetCreateFleet() components.CreateFleet {
	if c == nil {
		return components.CreateFleet{}
	}
	return c.CreateFleet
}
