// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateLocalLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateLocalLobbyGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateLocalLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (c *CreateLocalLobbySecurity) GetPlayerAuth() string {
	if c == nil {
		return ""
	}
	return c.PlayerAuth
}

type CreateLocalLobbyRequestBody struct {
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any               `json:"initialConfig"`
	Region        components.Region `json:"region"`
}

func (c *CreateLocalLobbyRequestBody) GetInitialConfig() any {
	if c == nil {
		return nil
	}
	return c.InitialConfig
}

func (c *CreateLocalLobbyRequestBody) GetRegion() components.Region {
	if c == nil {
		return components.Region("")
	}
	return c.Region
}

type CreateLocalLobbyRequest struct {
	AppID       *string                     `pathParam:"style=simple,explode=false,name=appId"`
	RoomID      *string                     `queryParam:"style=form,explode=true,name=roomId"`
	RequestBody CreateLocalLobbyRequestBody `request:"mediaType=application/json"`
}

func (c *CreateLocalLobbyRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateLocalLobbyRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreateLocalLobbyRequest) GetRequestBody() CreateLocalLobbyRequestBody {
	if c == nil {
		return CreateLocalLobbyRequestBody{}
	}
	return c.RequestBody
}
