// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreatePrivateLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreatePrivateLobbyGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreatePrivateLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (c *CreatePrivateLobbySecurity) GetPlayerAuth() string {
	if c == nil {
		return ""
	}
	return c.PlayerAuth
}

type CreatePrivateLobbyRequestBody struct {
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any               `json:"initialConfig"`
	Region        components.Region `json:"region"`
}

func (c *CreatePrivateLobbyRequestBody) GetInitialConfig() any {
	if c == nil {
		return nil
	}
	return c.InitialConfig
}

func (c *CreatePrivateLobbyRequestBody) GetRegion() components.Region {
	if c == nil {
		return components.Region("")
	}
	return c.Region
}

type CreatePrivateLobbyRequest struct {
	AppID       *string                       `pathParam:"style=simple,explode=false,name=appId"`
	RoomID      *string                       `queryParam:"style=form,explode=true,name=roomId"`
	RequestBody CreatePrivateLobbyRequestBody `request:"mediaType=application/json"`
}

func (c *CreatePrivateLobbyRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreatePrivateLobbyRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreatePrivateLobbyRequest) GetRequestBody() CreatePrivateLobbyRequestBody {
	if c == nil {
		return CreatePrivateLobbyRequestBody{}
	}
	return c.RequestBody
}
