// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateOrgTokenRequest struct {
	OrgID          string                    `pathParam:"style=simple,explode=false,name=orgId"`
	CreateOrgToken components.CreateOrgToken `request:"mediaType=application/json"`
}

func (c *CreateOrgTokenRequest) GetOrgID() string {
	if c == nil {
		return ""
	}
	return c.OrgID
}

func (c *CreateOrgTokenRequest) GetCreateOrgToken() components.CreateOrgToken {
	if c == nil {
		return components.CreateOrgToken{}
	}
	return c.CreateOrgToken
}
