// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateWithMultipartUploadsV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateWithMultipartUploadsV2DeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateWithMultipartUploadsV2DeprecatedRequest struct {
	AppID                      *string                               `pathParam:"style=simple,explode=false,name=appId"`
	CreateMultipartBuildParams components.CreateMultipartBuildParams `request:"mediaType=application/json"`
}

func (c *CreateWithMultipartUploadsV2DeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateWithMultipartUploadsV2DeprecatedRequest) GetCreateMultipartBuildParams() components.CreateMultipartBuildParams {
	if c == nil {
		return components.CreateMultipartBuildParams{}
	}
	return c.CreateMultipartBuildParams
}
