// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateBuildV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateBuildV2DeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateBuildV2DeprecatedRequest struct {
	AppID             *string                      `pathParam:"style=simple,explode=false,name=appId"`
	CreateBuildParams components.CreateBuildParams `request:"mediaType=application/json"`
}

func (c *CreateBuildV2DeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateBuildV2DeprecatedRequest) GetCreateBuildParams() components.CreateBuildParams {
	if c == nil {
		return components.CreateBuildParams{}
	}
	return c.CreateBuildParams
}
