// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateFleetGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (c *CreateFleetGlobals) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

type CreateFleetRequest struct {
	OrgID         *string                  `queryParam:"style=form,explode=true,name=orgId"`
	CreateFleetV2 components.CreateFleetV2 `request:"mediaType=application/json"`
}

func (c *CreateFleetRequest) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *CreateFleetRequest) GetCreateFleetV2() components.CreateFleetV2 {
	if c == nil {
		return components.CreateFleetV2{}
	}
	return c.CreateFleetV2
}
