// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateBuildGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (c *CreateBuildGlobals) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

type CreateBuildRequest struct {
	OrgID                      *string                               `queryParam:"style=form,explode=true,name=orgId"`
	CreateMultipartBuildParams components.CreateMultipartBuildParams `request:"mediaType=application/json"`
}

func (c *CreateBuildRequest) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *CreateBuildRequest) GetCreateMultipartBuildParams() components.CreateMultipartBuildParams {
	if c == nil {
		return components.CreateMultipartBuildParams{}
	}
	return c.CreateMultipartBuildParams
}
