// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateDeploymentV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateDeploymentV2DeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateDeploymentV2DeprecatedRequest struct {
	AppID              *string                       `pathParam:"style=simple,explode=false,name=appId"`
	BuildID            int                           `pathParam:"style=simple,explode=false,name=buildId"`
	DeploymentConfigV2 components.DeploymentConfigV2 `request:"mediaType=application/json"`
}

func (c *CreateDeploymentV2DeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateDeploymentV2DeprecatedRequest) GetBuildID() int {
	if c == nil {
		return 0
	}
	return c.BuildID
}

func (c *CreateDeploymentV2DeprecatedRequest) GetDeploymentConfigV2() components.DeploymentConfigV2 {
	if c == nil {
		return components.DeploymentConfigV2{}
	}
	return c.DeploymentConfigV2
}
