// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateProcessV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateProcessV2DeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateProcessV2DeprecatedRequest struct {
	AppID  *string           `pathParam:"style=simple,explode=false,name=appId"`
	Region components.Region `pathParam:"style=simple,explode=false,name=region"`
}

func (c *CreateProcessV2DeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateProcessV2DeprecatedRequest) GetRegion() components.Region {
	if c == nil {
		return components.Region("")
	}
	return c.Region
}
