// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateBuildRegistryGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (c *CreateBuildRegistryGlobals) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

type CreateBuildRegistryRequest struct {
	OrgID               *string                        `queryParam:"style=form,explode=true,name=orgId"`
	CreateBuildV3Params components.CreateBuildV3Params `request:"mediaType=application/json"`
}

func (c *CreateBuildRegistryRequest) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *CreateBuildRegistryRequest) GetCreateBuildV3Params() components.CreateBuildV3Params {
	if c == nil {
		return components.CreateBuildV3Params{}
	}
	return c.CreateBuildV3Params
}
