// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateRoomDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateRoomDeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateRoomDeprecatedRequest struct {
	AppID            *string                     `pathParam:"style=simple,explode=false,name=appId"`
	RoomID           *string                     `queryParam:"style=form,explode=true,name=roomId"`
	CreateRoomParams components.CreateRoomParams `request:"mediaType=application/json"`
}

func (c *CreateRoomDeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateRoomDeprecatedRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreateRoomDeprecatedRequest) GetCreateRoomParams() components.CreateRoomParams {
	if c == nil {
		return components.CreateRoomParams{}
	}
	return c.CreateRoomParams
}
