// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateLobbyGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (c *CreateLobbySecurity) GetPlayerAuth() string {
	if c == nil {
		return ""
	}
	return c.PlayerAuth
}

type CreateLobbyRequest struct {
	AppID               *string                        `pathParam:"style=simple,explode=false,name=appId"`
	ShortCode           *string                        `queryParam:"style=form,explode=true,name=shortCode"`
	RoomID              *string                        `queryParam:"style=form,explode=true,name=roomId"`
	CreateLobbyV3Params components.CreateLobbyV3Params `request:"mediaType=application/json"`
}

func (c *CreateLobbyRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateLobbyRequest) GetShortCode() *string {
	if c == nil {
		return nil
	}
	return c.ShortCode
}

func (c *CreateLobbyRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreateLobbyRequest) GetCreateLobbyV3Params() components.CreateLobbyV3Params {
	if c == nil {
		return components.CreateLobbyV3Params{}
	}
	return c.CreateLobbyV3Params
}
