// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreatePublicLobbyGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreatePublicLobbyGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreatePublicLobbySecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (c *CreatePublicLobbySecurity) GetPlayerAuth() string {
	if c == nil {
		return ""
	}
	return c.PlayerAuth
}

type CreatePublicLobbyRequestBody struct {
	// User input to initialize the game state. Object must be smaller than 64KB.
	InitialConfig any               `json:"initialConfig"`
	Region        components.Region `json:"region"`
}

func (c *CreatePublicLobbyRequestBody) GetInitialConfig() any {
	if c == nil {
		return nil
	}
	return c.InitialConfig
}

func (c *CreatePublicLobbyRequestBody) GetRegion() components.Region {
	if c == nil {
		return components.Region("")
	}
	return c.Region
}

type CreatePublicLobbyRequest struct {
	AppID       *string                      `pathParam:"style=simple,explode=false,name=appId"`
	RoomID      *string                      `queryParam:"style=form,explode=true,name=roomId"`
	RequestBody CreatePublicLobbyRequestBody `request:"mediaType=application/json"`
}

func (c *CreatePublicLobbyRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreatePublicLobbyRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreatePublicLobbyRequest) GetRequestBody() CreatePublicLobbyRequestBody {
	if c == nil {
		return CreatePublicLobbyRequestBody{}
	}
	return c.RequestBody
}
