// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateDeploymentGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateDeploymentRequest struct {
	AppID              *string                       `pathParam:"style=simple,explode=false,name=appId"`
	DeploymentConfigV3 components.DeploymentConfigV3 `request:"mediaType=application/json"`
}

func (c *CreateDeploymentRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateDeploymentRequest) GetDeploymentConfigV3() components.DeploymentConfigV3 {
	if c == nil {
		return components.DeploymentConfigV3{}
	}
	return c.DeploymentConfigV3
}
