// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type CreateLobbyDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateLobbyDeprecatedGlobals) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

type CreateLobbyDeprecatedSecurity struct {
	PlayerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (c *CreateLobbyDeprecatedSecurity) GetPlayerAuth() string {
	if c == nil {
		return ""
	}
	return c.PlayerAuth
}

type CreateLobbyDeprecatedRequest struct {
	AppID             *string                      `pathParam:"style=simple,explode=false,name=appId"`
	RoomID            *string                      `queryParam:"style=form,explode=true,name=roomId"`
	CreateLobbyParams components.CreateLobbyParams `request:"mediaType=application/json"`
}

func (c *CreateLobbyDeprecatedRequest) GetAppID() *string {
	if c == nil {
		return nil
	}
	return c.AppID
}

func (c *CreateLobbyDeprecatedRequest) GetRoomID() *string {
	if c == nil {
		return nil
	}
	return c.RoomID
}

func (c *CreateLobbyDeprecatedRequest) GetCreateLobbyParams() components.CreateLobbyParams {
	if c == nil {
		return components.CreateLobbyParams{}
	}
	return c.CreateLobbyParams
}
