// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteBuildDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DeleteBuildDeprecatedGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DeleteBuildDeprecatedRequest struct {
	AppID   *string `pathParam:"style=simple,explode=false,name=appId"`
	BuildID int     `pathParam:"style=simple,explode=false,name=buildId"`
}

func (d *DeleteBuildDeprecatedRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

func (d *DeleteBuildDeprecatedRequest) GetBuildID() int {
	if d == nil {
		return 0
	}
	return d.BuildID
}
