// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteAppV1DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DeleteAppV1DeprecatedGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DeleteAppV1DeprecatedRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DeleteAppV1DeprecatedRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}
