// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteAppGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DeleteAppGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DeleteAppRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DeleteAppRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}
