// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteBuildGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (d *DeleteBuildGlobals) GetOrgID() *string {
	if d == nil {
		return nil
	}
	return d.OrgID
}

type DeleteBuildRequest struct {
	BuildID string  `pathParam:"style=simple,explode=false,name=buildId"`
	OrgID   *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (d *DeleteBuildRequest) GetBuildID() string {
	if d == nil {
		return ""
	}
	return d.BuildID
}

func (d *DeleteBuildRequest) GetOrgID() *string {
	if d == nil {
		return nil
	}
	return d.OrgID
}
