// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type DeprecatedUpdateFleetRegionV2Globals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (d *DeprecatedUpdateFleetRegionV2Globals) GetOrgID() *string {
	if d == nil {
		return nil
	}
	return d.OrgID
}

type DeprecatedUpdateFleetRegionV2Request struct {
	FleetID           string                       `pathParam:"style=simple,explode=false,name=fleetId"`
	Region            components.Region            `pathParam:"style=simple,explode=false,name=region"`
	OrgID             *string                      `queryParam:"style=form,explode=true,name=orgId"`
	FleetRegionConfig components.FleetRegionConfig `request:"mediaType=application/json"`
}

func (d *DeprecatedUpdateFleetRegionV2Request) GetFleetID() string {
	if d == nil {
		return ""
	}
	return d.FleetID
}

func (d *DeprecatedUpdateFleetRegionV2Request) GetRegion() components.Region {
	if d == nil {
		return components.Region("")
	}
	return d.Region
}

func (d *DeprecatedUpdateFleetRegionV2Request) GetOrgID() *string {
	if d == nil {
		return nil
	}
	return d.OrgID
}

func (d *DeprecatedUpdateFleetRegionV2Request) GetFleetRegionConfig() components.FleetRegionConfig {
	if d == nil {
		return components.FleetRegionConfig{}
	}
	return d.FleetRegionConfig
}
