// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DestroyRoomDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DestroyRoomDeprecatedGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DestroyRoomDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (d *DestroyRoomDeprecatedRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

func (d *DestroyRoomDeprecatedRequest) GetRoomID() string {
	if d == nil {
		return ""
	}
	return d.RoomID
}
