// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DestroyRoomGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DestroyRoomGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DestroyRoomRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (d *DestroyRoomRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

func (d *DestroyRoomRequest) GetRoomID() string {
	if d == nil {
		return ""
	}
	return d.RoomID
}
