// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DownloadLogForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (d *DownloadLogForProcessGlobals) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

type DownloadLogForProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (d *DownloadLogForProcessRequest) GetAppID() *string {
	if d == nil {
		return nil
	}
	return d.AppID
}

func (d *DownloadLogForProcessRequest) GetProcessID() string {
	if d == nil {
		return ""
	}
	return d.ProcessID
}
