// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAppGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetAppGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetAppRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetAppRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
