// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetActiveRoomsForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetActiveRoomsForProcessGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetActiveRoomsForProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetActiveRoomsForProcessRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetActiveRoomsForProcessRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
