// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAppsGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetAppsGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetAppsRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetAppsRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
