// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetActiveRoomsForProcessDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetActiveRoomsForProcessDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetActiveRoomsForProcessDeprecatedRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetActiveRoomsForProcessDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetActiveRoomsForProcessDeprecatedRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
