// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetBuildsV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetBuildsV2DeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetBuildsV2DeprecatedRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetBuildsV2DeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
