// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetBuildInfoDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetBuildInfoDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetBuildInfoDeprecatedRequest struct {
	AppID   *string `pathParam:"style=simple,explode=false,name=appId"`
	BuildID int     `pathParam:"style=simple,explode=false,name=buildId"`
}

func (g *GetBuildInfoDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetBuildInfoDeprecatedRequest) GetBuildID() int {
	if g == nil {
		return 0
	}
	return g.BuildID
}
