// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConnectionInfoDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetConnectionInfoDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetConnectionInfoDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (g *GetConnectionInfoDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetConnectionInfoDeprecatedRequest) GetRoomID() string {
	if g == nil {
		return ""
	}
	return g.RoomID
}
