// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConnectionInfoGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetConnectionInfoGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetConnectionInfoRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (g *GetConnectionInfoRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetConnectionInfoRequest) GetRoomID() string {
	if g == nil {
		return ""
	}
	return g.RoomID
}
