// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetDeploymentGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetDeploymentRequest struct {
	AppID        *string `pathParam:"style=simple,explode=false,name=appId"`
	DeploymentID string  `pathParam:"style=simple,explode=false,name=deploymentId"`
}

func (g *GetDeploymentRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetDeploymentRequest) GetDeploymentID() string {
	if g == nil {
		return ""
	}
	return g.DeploymentID
}
