// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetDeploymentInfoV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetDeploymentInfoV2DeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetDeploymentInfoV2DeprecatedRequest struct {
	AppID        *string `pathParam:"style=simple,explode=false,name=appId"`
	DeploymentID int     `pathParam:"style=simple,explode=false,name=deploymentId"`
}

func (g *GetDeploymentInfoV2DeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetDeploymentInfoV2DeprecatedRequest) GetDeploymentID() int {
	if g == nil {
		return 0
	}
	return g.DeploymentID
}
