// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetDeploymentsGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetDeploymentsGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetDeploymentsRequest struct {
	AppID         *string `pathParam:"style=simple,explode=false,name=appId"`
	DeploymentTag *string `queryParam:"style=form,explode=true,name=deploymentTag"`
	BuildTag      *string `queryParam:"style=form,explode=true,name=buildTag"`
}

func (g *GetDeploymentsRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetDeploymentsRequest) GetDeploymentTag() *string {
	if g == nil {
		return nil
	}
	return g.DeploymentTag
}

func (g *GetDeploymentsRequest) GetBuildTag() *string {
	if g == nil {
		return nil
	}
	return g.BuildTag
}
