// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFleetsDeprecatedGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetsDeprecatedGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetsDeprecatedRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetsDeprecatedRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
