// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFleetsGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetsGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetsRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetsRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
