// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFleetGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetRequest struct {
	FleetID string  `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID   *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetRequest) GetFleetID() string {
	if g == nil {
		return ""
	}
	return g.FleetID
}

func (g *GetFleetRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
