// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetFleetMetricsDeprecatedGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetMetricsDeprecatedGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetMetricsDeprecatedRequest struct {
	FleetID string `pathParam:"style=simple,explode=false,name=fleetId"`
	// Available metrics to query over time.
	Metrics []components.FleetMetricName `queryParam:"style=form,explode=true,name=metrics"`
	End     *float64                     `queryParam:"style=form,explode=true,name=end"`
	// Unix timestamp. Default is -1 hour from `end`.
	Start *float64 `queryParam:"style=form,explode=true,name=start"`
	Step  *int     `default:"60" queryParam:"style=form,explode=true,name=step"`
	OrgID *string  `queryParam:"style=form,explode=true,name=orgId"`
}

func (g GetFleetMetricsDeprecatedRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFleetMetricsDeprecatedRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"fleetId"}); err != nil {
		return err
	}
	return nil
}

func (g *GetFleetMetricsDeprecatedRequest) GetFleetID() string {
	if g == nil {
		return ""
	}
	return g.FleetID
}

func (g *GetFleetMetricsDeprecatedRequest) GetMetrics() []components.FleetMetricName {
	if g == nil {
		return nil
	}
	return g.Metrics
}

func (g *GetFleetMetricsDeprecatedRequest) GetEnd() *float64 {
	if g == nil {
		return nil
	}
	return g.End
}

func (g *GetFleetMetricsDeprecatedRequest) GetStart() *float64 {
	if g == nil {
		return nil
	}
	return g.Start
}

func (g *GetFleetMetricsDeprecatedRequest) GetStep() *int {
	if g == nil {
		return nil
	}
	return g.Step
}

func (g *GetFleetMetricsDeprecatedRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
