// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetFleetDeprecatedGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetDeprecatedGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetDeprecatedRequest struct {
	FleetID string  `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID   *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetDeprecatedRequest) GetFleetID() string {
	if g == nil {
		return ""
	}
	return g.FleetID
}

func (g *GetFleetDeprecatedRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
