// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetFleetMetricsGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetMetricsGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetMetricsRequest struct {
	FleetID string            `pathParam:"style=simple,explode=false,name=fleetId"`
	Region  components.Region `pathParam:"style=simple,explode=false,name=region"`
	// Available metrics to query over time.
	Metrics []components.FleetMetricName `queryParam:"style=form,explode=true,name=metrics"`
	End     *float64                     `queryParam:"style=form,explode=true,name=end"`
	// Unix timestamp. Default is -1 hour from `end`.
	Start *float64 `queryParam:"style=form,explode=true,name=start"`
	Step  *int     `default:"60" queryParam:"style=form,explode=true,name=step"`
	OrgID *string  `queryParam:"style=form,explode=true,name=orgId"`
}

func (g GetFleetMetricsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFleetMetricsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"fleetId", "region"}); err != nil {
		return err
	}
	return nil
}

func (g *GetFleetMetricsRequest) GetFleetID() string {
	if g == nil {
		return ""
	}
	return g.FleetID
}

func (g *GetFleetMetricsRequest) GetRegion() components.Region {
	if g == nil {
		return components.Region("")
	}
	return g.Region
}

func (g *GetFleetMetricsRequest) GetMetrics() []components.FleetMetricName {
	if g == nil {
		return nil
	}
	return g.Metrics
}

func (g *GetFleetMetricsRequest) GetEnd() *float64 {
	if g == nil {
		return nil
	}
	return g.End
}

func (g *GetFleetMetricsRequest) GetStart() *float64 {
	if g == nil {
		return nil
	}
	return g.Start
}

func (g *GetFleetMetricsRequest) GetStep() *int {
	if g == nil {
		return nil
	}
	return g.Step
}

func (g *GetFleetMetricsRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
