// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetFleetRegionGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetRegionGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetFleetRegionRequest struct {
	FleetID string            `pathParam:"style=simple,explode=false,name=fleetId"`
	Region  components.Region `pathParam:"style=simple,explode=false,name=region"`
	OrgID   *string           `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetFleetRegionRequest) GetFleetID() string {
	if g == nil {
		return ""
	}
	return g.FleetID
}

func (g *GetFleetRegionRequest) GetRegion() components.Region {
	if g == nil {
		return components.Region("")
	}
	return g.Region
}

func (g *GetFleetRegionRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
