// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetInactiveRoomsForProcessDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetInactiveRoomsForProcessDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetInactiveRoomsForProcessDeprecatedRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetInactiveRoomsForProcessDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetInactiveRoomsForProcessDeprecatedRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
