// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetInvoicesGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetInvoicesGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetInvoicesRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetInvoicesRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
