// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetInactiveRoomsForProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetInactiveRoomsForProcessGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetInactiveRoomsForProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetInactiveRoomsForProcessRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetInactiveRoomsForProcessRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
