// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetLatestProcessesV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestProcessesV2DeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLatestProcessesV2DeprecatedRequest struct {
	AppID  *string                    `pathParam:"style=simple,explode=false,name=appId"`
	Status []components.ProcessStatus `queryParam:"style=form,explode=true,name=status"`
	Region []components.Region        `queryParam:"style=form,explode=true,name=region"`
}

func (g *GetLatestProcessesV2DeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetLatestProcessesV2DeprecatedRequest) GetStatus() []components.ProcessStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetLatestProcessesV2DeprecatedRequest) GetRegion() []components.Region {
	if g == nil {
		return nil
	}
	return g.Region
}
