// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLatestDeploymentV1DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestDeploymentV1DeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLatestDeploymentV1DeprecatedRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestDeploymentV1DeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
