// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLatestDeploymentGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestDeploymentGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLatestDeploymentRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestDeploymentRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}
