// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetLatestProcessesGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLatestProcessesGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLatestProcessesRequest struct {
	AppID  *string                    `pathParam:"style=simple,explode=false,name=appId"`
	Status []components.ProcessStatus `queryParam:"style=form,explode=true,name=status"`
	Region []components.Region        `queryParam:"style=form,explode=true,name=region"`
	Before *float64                   `queryParam:"style=form,explode=true,name=before"`
}

func (g *GetLatestProcessesRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetLatestProcessesRequest) GetStatus() []components.ProcessStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetLatestProcessesRequest) GetRegion() []components.Region {
	if g == nil {
		return nil
	}
	return g.Region
}

func (g *GetLatestProcessesRequest) GetBefore() *float64 {
	if g == nil {
		return nil
	}
	return g.Before
}
