// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLobbyInfoByShortCodeGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLobbyInfoByShortCodeGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLobbyInfoByShortCodeRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ShortCode string  `pathParam:"style=simple,explode=false,name=shortCode"`
}

func (g *GetLobbyInfoByShortCodeRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetLobbyInfoByShortCodeRequest) GetShortCode() string {
	if g == nil {
		return ""
	}
	return g.ShortCode
}
