// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLobbyInfoGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetLobbyInfoGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetLobbyInfoRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (g *GetLobbyInfoRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetLobbyInfoRequest) GetRoomID() string {
	if g == nil {
		return ""
	}
	return g.RoomID
}
