// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetNodeShapesGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetNodeShapesGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetNodeShapesRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetNodeShapesRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
