// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetNodeRequest struct {
	NodeID string `pathParam:"style=simple,explode=false,name=nodeId"`
}

func (g *GetNodeRequest) GetNodeID() string {
	if g == nil {
		return ""
	}
	return g.NodeID
}
