// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetOrgPendingInvitesRequest struct {
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

func (g *GetOrgPendingInvitesRequest) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}
