// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPaymentMethodGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetPaymentMethodGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetPaymentMethodRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetPaymentMethodRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
