// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetProcessGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetProcessRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetProcessRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
