// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetProcessesCountExperimentalGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetProcessesCountExperimentalGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetProcessesCountExperimentalRequest struct {
	AppID  *string                    `pathParam:"style=simple,explode=false,name=appId"`
	Status []components.ProcessStatus `queryParam:"style=form,explode=true,name=status"`
	Region []components.Region        `queryParam:"style=form,explode=true,name=region"`
	Before *float64                   `queryParam:"style=form,explode=true,name=before"`
}

func (g *GetProcessesCountExperimentalRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetProcessesCountExperimentalRequest) GetStatus() []components.ProcessStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetProcessesCountExperimentalRequest) GetRegion() []components.Region {
	if g == nil {
		return nil
	}
	return g.Region
}

func (g *GetProcessesCountExperimentalRequest) GetBefore() *float64 {
	if g == nil {
		return nil
	}
	return g.Before
}

// GetProcessesCountExperimentalResponseBody - Ok
type GetProcessesCountExperimentalResponseBody struct {
	Count float64 `json:"count"`
}

func (g *GetProcessesCountExperimentalResponseBody) GetCount() float64 {
	if g == nil {
		return 0.0
	}
	return g.Count
}
