// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetProcessInfoDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetProcessInfoDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetProcessInfoDeprecatedRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (g *GetProcessInfoDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetProcessInfoDeprecatedRequest) GetProcessID() string {
	if g == nil {
		return ""
	}
	return g.ProcessID
}
