// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetRoomInfoGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetRoomInfoGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetRoomInfoRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (g *GetRoomInfoRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetRoomInfoRequest) GetRoomID() string {
	if g == nil {
		return ""
	}
	return g.RoomID
}
