// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetRoomInfoDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetRoomInfoDeprecatedGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetRoomInfoDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (g *GetRoomInfoDeprecatedRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetRoomInfoDeprecatedRequest) GetRoomID() string {
	if g == nil {
		return ""
	}
	return g.RoomID
}
