// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type GetStoppedProcessesGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetStoppedProcessesGlobals) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

type GetStoppedProcessesRequest struct {
	AppID  *string            `pathParam:"style=simple,explode=false,name=appId"`
	Region *components.Region `queryParam:"style=form,explode=true,name=region"`
}

func (g *GetStoppedProcessesRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetStoppedProcessesRequest) GetRegion() *components.Region {
	if g == nil {
		return nil
	}
	return g.Region
}
