// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetUpcomingInvoiceTotalGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUpcomingInvoiceTotalGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetUpcomingInvoiceTotalRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUpcomingInvoiceTotalRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

// GetUpcomingInvoiceTotalResponseBody - Ok
type GetUpcomingInvoiceTotalResponseBody struct {
	Value float64 `json:"value"`
}

func (g *GetUpcomingInvoiceTotalResponseBody) GetValue() float64 {
	if g == nil {
		return 0.0
	}
	return g.Value
}
