// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetUsageLimitsGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUsageLimitsGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetUsageLimitsRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUsageLimitsRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
