// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetUpcomingInvoiceItemsGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUpcomingInvoiceItemsGlobals) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}

type GetUpcomingInvoiceItemsRequest struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetUpcomingInvoiceItemsRequest) GetOrgID() *string {
	if g == nil {
		return nil
	}
	return g.OrgID
}
