// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type InitStripeCustomerPortalURLGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (i *InitStripeCustomerPortalURLGlobals) GetOrgID() *string {
	if i == nil {
		return nil
	}
	return i.OrgID
}

type InitStripeCustomerPortalURLRequest struct {
	OrgID             *string                      `queryParam:"style=form,explode=true,name=orgId"`
	CustomerPortalURL components.CustomerPortalURL `request:"mediaType=application/json"`
}

func (i *InitStripeCustomerPortalURLRequest) GetOrgID() *string {
	if i == nil {
		return nil
	}
	return i.OrgID
}

func (i *InitStripeCustomerPortalURLRequest) GetCustomerPortalURL() components.CustomerPortalURL {
	if i == nil {
		return components.CustomerPortalURL{}
	}
	return i.CustomerPortalURL
}
