// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type InviteUserRequest struct {
	OrgID            string                      `pathParam:"style=simple,explode=false,name=orgId"`
	CreateUserInvite components.CreateUserInvite `request:"mediaType=application/json"`
}

func (i *InviteUserRequest) GetOrgID() string {
	if i == nil {
		return ""
	}
	return i.OrgID
}

func (i *InviteUserRequest) GetCreateUserInvite() components.CreateUserInvite {
	if i == nil {
		return components.CreateUserInvite{}
	}
	return i.CreateUserInvite
}
