// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type ListProvisionedNodesGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (l *ListProvisionedNodesGlobals) GetOrgID() *string {
	if l == nil {
		return nil
	}
	return l.OrgID
}

type ListProvisionedNodesRequest struct {
	FleetID string             `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID   *string            `queryParam:"style=form,explode=true,name=orgId"`
	Region  *components.Region `queryParam:"style=form,explode=true,name=region"`
}

func (l *ListProvisionedNodesRequest) GetFleetID() string {
	if l == nil {
		return ""
	}
	return l.FleetID
}

func (l *ListProvisionedNodesRequest) GetOrgID() *string {
	if l == nil {
		return nil
	}
	return l.OrgID
}

func (l *ListProvisionedNodesRequest) GetRegion() *components.Region {
	if l == nil {
		return nil
	}
	return l.Region
}
