// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/internal/utils"
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type ListActivePublicLobbiesDeprecatedV1Globals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (l *ListActivePublicLobbiesDeprecatedV1Globals) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

type ListActivePublicLobbiesDeprecatedV1Request struct {
	AppID  *string            `pathParam:"style=simple,explode=false,name=appId"`
	Local  *bool              `default:"false" queryParam:"style=form,explode=true,name=local"`
	Region *components.Region `queryParam:"style=form,explode=true,name=region"`
}

func (l ListActivePublicLobbiesDeprecatedV1Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListActivePublicLobbiesDeprecatedV1Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListActivePublicLobbiesDeprecatedV1Request) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

func (l *ListActivePublicLobbiesDeprecatedV1Request) GetLocal() *bool {
	if l == nil {
		return nil
	}
	return l.Local
}

func (l *ListActivePublicLobbiesDeprecatedV1Request) GetRegion() *components.Region {
	if l == nil {
		return nil
	}
	return l.Region
}
