// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type ListActivePublicLobbiesGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (l *ListActivePublicLobbiesGlobals) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

type ListActivePublicLobbiesRequest struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
	// If omitted, active public lobbies in all regions will be returned.
	Region *components.Region `queryParam:"style=form,explode=true,name=region"`
}

func (l *ListActivePublicLobbiesRequest) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

func (l *ListActivePublicLobbiesRequest) GetRegion() *components.Region {
	if l == nil {
		return nil
	}
	return l.Region
}
