// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type LoginNicknameGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (l *LoginNicknameGlobals) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

type LoginNicknameRequest struct {
	AppID          *string                   `pathParam:"style=simple,explode=false,name=appId"`
	NicknameObject components.NicknameObject `request:"mediaType=application/json"`
}

func (l *LoginNicknameRequest) GetAppID() *string {
	if l == nil {
		return nil
	}
	return l.AppID
}

func (l *LoginNicknameRequest) GetNicknameObject() components.NicknameObject {
	if l == nil {
		return components.NicknameObject{}
	}
	return l.NicknameObject
}
