// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type PatchAppGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (p *PatchAppGlobals) GetAppID() *string {
	if p == nil {
		return nil
	}
	return p.AppID
}

type PatchAppRequest struct {
	AppID                             *string                                      `pathParam:"style=simple,explode=false,name=appId"`
	PartialAppConfigWithServiceConfig components.PartialAppConfigWithServiceConfig `request:"mediaType=application/json"`
}

func (p *PatchAppRequest) GetAppID() *string {
	if p == nil {
		return nil
	}
	return p.AppID
}

func (p *PatchAppRequest) GetPartialAppConfigWithServiceConfig() components.PartialAppConfigWithServiceConfig {
	if p == nil {
		return components.PartialAppConfigWithServiceConfig{}
	}
	return p.PartialAppConfigWithServiceConfig
}
