// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RejectInviteRequest struct {
	OrgID string `pathParam:"style=simple,explode=false,name=orgId"`
}

func (r *RejectInviteRequest) GetOrgID() string {
	if r == nil {
		return ""
	}
	return r.OrgID
}
