// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ResumeRoomGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (r *ResumeRoomGlobals) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

type ResumeRoomRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (r *ResumeRoomRequest) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

func (r *ResumeRoomRequest) GetRoomID() string {
	if r == nil {
		return ""
	}
	return r.RoomID
}
