// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ResumeRoomGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *ResumeRoomGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type ResumeRoomRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (o *ResumeRoomRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *ResumeRoomRequest) GetRoomID() string {
	if o == nil {
		return ""
	}
	return o.RoomID
}
