// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RevokeOrgTokenRequest struct {
	OrgID      string `pathParam:"style=simple,explode=false,name=orgId"`
	OrgTokenID string `pathParam:"style=simple,explode=false,name=orgTokenId"`
}

func (r *RevokeOrgTokenRequest) GetOrgID() string {
	if r == nil {
		return ""
	}
	return r.OrgID
}

func (r *RevokeOrgTokenRequest) GetOrgTokenID() string {
	if r == nil {
		return ""
	}
	return r.OrgTokenID
}
