// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RunBuildDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (r *RunBuildDeprecatedGlobals) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

type RunBuildDeprecatedRequestBody struct {
	File File `multipartForm:"file,name=file"`
}

func (r *RunBuildDeprecatedRequestBody) GetFile() File {
	if r == nil {
		return File{}
	}
	return r.File
}

type RunBuildDeprecatedRequest struct {
	AppID       *string                       `pathParam:"style=simple,explode=false,name=appId"`
	BuildID     int                           `pathParam:"style=simple,explode=false,name=buildId"`
	RequestBody RunBuildDeprecatedRequestBody `request:"mediaType=multipart/form-data"`
}

func (r *RunBuildDeprecatedRequest) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

func (r *RunBuildDeprecatedRequest) GetBuildID() int {
	if r == nil {
		return 0
	}
	return r.BuildID
}

func (r *RunBuildDeprecatedRequest) GetRequestBody() RunBuildDeprecatedRequestBody {
	if r == nil {
		return RunBuildDeprecatedRequestBody{}
	}
	return r.RequestBody
}
