// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RunBuildV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (r *RunBuildV2DeprecatedGlobals) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

type RunBuildV2DeprecatedFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (r *RunBuildV2DeprecatedFile) GetFileName() string {
	if r == nil {
		return ""
	}
	return r.FileName
}

func (r *RunBuildV2DeprecatedFile) GetContent() any {
	if r == nil {
		return nil
	}
	return r.Content
}

type RunBuildV2DeprecatedRequestBody struct {
	File *RunBuildV2DeprecatedFile `multipartForm:"file,name=file"`
}

func (r *RunBuildV2DeprecatedRequestBody) GetFile() *RunBuildV2DeprecatedFile {
	if r == nil {
		return nil
	}
	return r.File
}

type RunBuildV2DeprecatedRequest struct {
	AppID       *string                         `pathParam:"style=simple,explode=false,name=appId"`
	BuildID     int                             `pathParam:"style=simple,explode=false,name=buildId"`
	RequestBody RunBuildV2DeprecatedRequestBody `request:"mediaType=multipart/form-data"`
}

func (r *RunBuildV2DeprecatedRequest) GetAppID() *string {
	if r == nil {
		return nil
	}
	return r.AppID
}

func (r *RunBuildV2DeprecatedRequest) GetBuildID() int {
	if r == nil {
		return 0
	}
	return r.BuildID
}

func (r *RunBuildV2DeprecatedRequest) GetRequestBody() RunBuildV2DeprecatedRequestBody {
	if r == nil {
		return RunBuildV2DeprecatedRequestBody{}
	}
	return r.RequestBody
}
