// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type RunBuildRegistryGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (o *RunBuildRegistryGlobals) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

type RunBuildRegistryRequest struct {
	BuildID        string                    `pathParam:"style=simple,explode=false,name=buildId"`
	OrgID          *string                   `queryParam:"style=form,explode=true,name=orgId"`
	RegistryConfig components.RegistryConfig `request:"mediaType=application/json"`
}

func (o *RunBuildRegistryRequest) GetBuildID() string {
	if o == nil {
		return ""
	}
	return o.BuildID
}

func (o *RunBuildRegistryRequest) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *RunBuildRegistryRequest) GetRegistryConfig() components.RegistryConfig {
	if o == nil {
		return components.RegistryConfig{}
	}
	return o.RegistryConfig
}
