// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type RunBuildGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (r *RunBuildGlobals) GetOrgID() *string {
	if r == nil {
		return nil
	}
	return r.OrgID
}

type RunBuildRequest struct {
	BuildID string  `pathParam:"style=simple,explode=false,name=buildId"`
	OrgID   *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (r *RunBuildRequest) GetBuildID() string {
	if r == nil {
		return ""
	}
	return r.BuildID
}

func (r *RunBuildRequest) GetOrgID() *string {
	if r == nil {
		return nil
	}
	return r.OrgID
}
