// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type SetLobbyStateGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (s *SetLobbyStateGlobals) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

type SetLobbyStateRequest struct {
	AppID               *string                        `pathParam:"style=simple,explode=false,name=appId"`
	RoomID              string                         `pathParam:"style=simple,explode=false,name=roomId"`
	SetLobbyStateParams components.SetLobbyStateParams `request:"mediaType=application/json"`
}

func (s *SetLobbyStateRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *SetLobbyStateRequest) GetRoomID() string {
	if s == nil {
		return ""
	}
	return s.RoomID
}

func (s *SetLobbyStateRequest) GetSetLobbyStateParams() components.SetLobbyStateParams {
	if s == nil {
		return components.SetLobbyStateParams{}
	}
	return s.SetLobbyStateParams
}
