// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type StopProcessGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (s *StopProcessGlobals) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

type StopProcessRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (s *StopProcessRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *StopProcessRequest) GetProcessID() string {
	if s == nil {
		return ""
	}
	return s.ProcessID
}
