// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type StopProcessV2DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (s *StopProcessV2DeprecatedGlobals) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

type StopProcessV2DeprecatedRequest struct {
	AppID     *string `pathParam:"style=simple,explode=false,name=appId"`
	ProcessID string  `pathParam:"style=simple,explode=false,name=processId"`
}

func (s *StopProcessV2DeprecatedRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *StopProcessV2DeprecatedRequest) GetProcessID() string {
	if s == nil {
		return ""
	}
	return s.ProcessID
}
