// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type SuspendRoomDeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (s *SuspendRoomDeprecatedGlobals) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

type SuspendRoomDeprecatedRequest struct {
	AppID  *string `pathParam:"style=simple,explode=false,name=appId"`
	RoomID string  `pathParam:"style=simple,explode=false,name=roomId"`
}

func (s *SuspendRoomDeprecatedRequest) GetAppID() *string {
	if s == nil {
		return nil
	}
	return s.AppID
}

func (s *SuspendRoomDeprecatedRequest) GetRoomID() string {
	if s == nil {
		return ""
	}
	return s.RoomID
}
