// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateRoomConfigGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (u *UpdateRoomConfigGlobals) GetAppID() *string {
	if u == nil {
		return nil
	}
	return u.AppID
}

type UpdateRoomConfigRequest struct {
	AppID                  *string                           `pathParam:"style=simple,explode=false,name=appId"`
	RoomID                 string                            `pathParam:"style=simple,explode=false,name=roomId"`
	UpdateRoomConfigParams components.UpdateRoomConfigParams `request:"mediaType=application/json"`
}

func (u *UpdateRoomConfigRequest) GetAppID() *string {
	if u == nil {
		return nil
	}
	return u.AppID
}

func (u *UpdateRoomConfigRequest) GetRoomID() string {
	if u == nil {
		return ""
	}
	return u.RoomID
}

func (u *UpdateRoomConfigRequest) GetUpdateRoomConfigParams() components.UpdateRoomConfigParams {
	if u == nil {
		return components.UpdateRoomConfigParams{}
	}
	return u.UpdateRoomConfigParams
}
