// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateFleetGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (u *UpdateFleetGlobals) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

type UpdateFleetRequest struct {
	FleetID       string                   `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID         *string                  `queryParam:"style=form,explode=true,name=orgId"`
	UpdateFleetV2 components.UpdateFleetV2 `request:"mediaType=application/json"`
}

func (u *UpdateFleetRequest) GetFleetID() string {
	if u == nil {
		return ""
	}
	return u.FleetID
}

func (u *UpdateFleetRequest) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UpdateFleetRequest) GetUpdateFleetV2() components.UpdateFleetV2 {
	if u == nil {
		return components.UpdateFleetV2{}
	}
	return u.UpdateFleetV2
}
