// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateFleetRegionGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (u *UpdateFleetRegionGlobals) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

type UpdateFleetRegionRequest struct {
	FleetID             string                         `pathParam:"style=simple,explode=false,name=fleetId"`
	Region              components.Region              `pathParam:"style=simple,explode=false,name=region"`
	OrgID               *string                        `queryParam:"style=form,explode=true,name=orgId"`
	FleetRegionConfigV2 components.FleetRegionConfigV2 `request:"mediaType=application/json"`
}

func (u *UpdateFleetRegionRequest) GetFleetID() string {
	if u == nil {
		return ""
	}
	return u.FleetID
}

func (u *UpdateFleetRegionRequest) GetRegion() components.Region {
	if u == nil {
		return components.Region("")
	}
	return u.Region
}

func (u *UpdateFleetRegionRequest) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UpdateFleetRegionRequest) GetFleetRegionConfigV2() components.FleetRegionConfigV2 {
	if u == nil {
		return components.FleetRegionConfigV2{}
	}
	return u.FleetRegionConfigV2
}
