// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateFleetDeprecatedGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (u *UpdateFleetDeprecatedGlobals) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

type UpdateFleetDeprecatedRequest struct {
	FleetID     string                 `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID       *string                `queryParam:"style=form,explode=true,name=orgId"`
	UpdateFleet components.UpdateFleet `request:"mediaType=application/json"`
}

func (u *UpdateFleetDeprecatedRequest) GetFleetID() string {
	if u == nil {
		return ""
	}
	return u.FleetID
}

func (u *UpdateFleetDeprecatedRequest) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UpdateFleetDeprecatedRequest) GetUpdateFleet() components.UpdateFleet {
	if u == nil {
		return components.UpdateFleet{}
	}
	return u.UpdateFleet
}
