// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateFleetGlobals struct {
	OrgID *string `queryParam:"style=form,explode=true,name=orgId"`
}

func (u *UpdateFleetGlobals) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

type UpdateFleetRequest struct {
	FleetID     string                 `pathParam:"style=simple,explode=false,name=fleetId"`
	OrgID       *string                `queryParam:"style=form,explode=true,name=orgId"`
	UpdateFleet components.UpdateFleet `request:"mediaType=application/json"`
}

func (u *UpdateFleetRequest) GetFleetID() string {
	if u == nil {
		return ""
	}
	return u.FleetID
}

func (u *UpdateFleetRequest) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UpdateFleetRequest) GetUpdateFleet() components.UpdateFleet {
	if u == nil {
		return components.UpdateFleet{}
	}
	return u.UpdateFleet
}
