// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateAppGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *UpdateAppGlobals) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

type UpdateAppRequest struct {
	AppID                      *string                               `pathParam:"style=simple,explode=false,name=appId"`
	AppConfigWithServiceConfig components.AppConfigWithServiceConfig `request:"mediaType=application/json"`
}

func (o *UpdateAppRequest) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *UpdateAppRequest) GetAppConfigWithServiceConfig() components.AppConfigWithServiceConfig {
	if o == nil {
		return components.AppConfigWithServiceConfig{}
	}
	return o.AppConfigWithServiceConfig
}
