// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateAppV1DeprecatedGlobals struct {
	AppID *string `pathParam:"style=simple,explode=false,name=appId"`
}

func (u *UpdateAppV1DeprecatedGlobals) GetAppID() *string {
	if u == nil {
		return nil
	}
	return u.AppID
}

type UpdateAppV1DeprecatedRequest struct {
	AppID           *string                    `pathParam:"style=simple,explode=false,name=appId"`
	CreateAppConfig components.CreateAppConfig `request:"mediaType=application/json"`
}

func (u *UpdateAppV1DeprecatedRequest) GetAppID() *string {
	if u == nil {
		return nil
	}
	return u.AppID
}

func (u *UpdateAppV1DeprecatedRequest) GetCreateAppConfig() components.CreateAppConfig {
	if u == nil {
		return components.CreateAppConfig{}
	}
	return u.CreateAppConfig
}
