// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hathora/cloud-sdk-go/hathoracloud/models/components"
)

type UpdateUserInviteRequest struct {
	OrgID            string                      `pathParam:"style=simple,explode=false,name=orgId"`
	UpdateUserInvite components.UpdateUserInvite `request:"mediaType=application/json"`
}

func (u *UpdateUserInviteRequest) GetOrgID() string {
	if u == nil {
		return ""
	}
	return u.OrgID
}

func (u *UpdateUserInviteRequest) GetUpdateUserInvite() components.UpdateUserInvite {
	if u == nil {
		return components.UpdateUserInvite{}
	}
	return u.UpdateUserInvite
}
